import { 
  Prescription, 
  Medication, 
  Pharmacy, 
  FormularyEntry,
  DrugInteraction 
} from '../../models/prescription.model';

// Common medications database
export const MOCK_MEDICATIONS: Medication[] = [
  {
    id: 'med-001',
    name: 'Lisinopril',
    genericName: 'Lisinopril',
    brandNames: ['Prinivil', 'Zestril'],
    ndc: '00093-7180-01',
    rxcui: '104377',
    form: 'tablet',
    strength: '10',
    strengthUnit: 'mg',
    manufacturer: 'Teva Pharmaceuticals',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Cardiovascular Agents',
    pharmacologicClass: 'ACE Inhibitors',
    warnings: ['May cause persistent cough', 'Risk of angioedema'],
    contraindications: ['Pregnancy', 'History of angioedema with ACE inhibitors'],
  },
  {
    id: 'med-002',
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    brandNames: ['Glucophage', 'Fortamet'],
    ndc: '00591-0584-01',
    rxcui: '6809',
    form: 'tablet',
    strength: '500',
    strengthUnit: 'mg',
    manufacturer: 'Mylan Pharmaceuticals',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Metabolic Agents',
    pharmacologicClass: 'Biguanides',
    warnings: ['Risk of lactic acidosis', 'Hold before contrast procedures'],
    contraindications: ['Renal impairment (eGFR <30)', 'Metabolic acidosis'],
  },
  {
    id: 'med-003',
    name: 'Atorvastatin',
    genericName: 'Atorvastatin Calcium',
    brandNames: ['Lipitor'],
    ndc: '00071-0155-23',
    rxcui: '617314',
    form: 'tablet',
    strength: '20',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Cardiovascular Agents',
    pharmacologicClass: 'HMG-CoA Reductase Inhibitors (Statins)',
    warnings: ['Risk of myopathy/rhabdomyolysis', 'Monitor liver function'],
    contraindications: ['Active liver disease', 'Pregnancy'],
  },
  {
    id: 'med-004',
    name: 'Omeprazole',
    genericName: 'Omeprazole',
    brandNames: ['Prilosec'],
    ndc: '00186-5020-31',
    rxcui: '7646',
    form: 'capsule',
    strength: '20',
    strengthUnit: 'mg',
    manufacturer: 'AstraZeneca',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Gastrointestinal Agents',
    pharmacologicClass: 'Proton Pump Inhibitors',
    warnings: ['Long-term use may increase fracture risk', 'May mask gastric cancer symptoms'],
    contraindications: [],
  },
  {
    id: 'med-005',
    name: 'Amlodipine',
    genericName: 'Amlodipine Besylate',
    brandNames: ['Norvasc'],
    ndc: '00069-1520-30',
    rxcui: '17767',
    form: 'tablet',
    strength: '5',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Cardiovascular Agents',
    pharmacologicClass: 'Calcium Channel Blockers',
    warnings: ['May cause peripheral edema', 'May worsen angina on initiation'],
    contraindications: [],
  },
  {
    id: 'med-006',
    name: 'Hydrocodone-Acetaminophen',
    genericName: 'Hydrocodone Bitartrate and Acetaminophen',
    brandNames: ['Vicodin', 'Norco', 'Lortab'],
    ndc: '00591-0385-01',
    rxcui: '857001',
    form: 'tablet',
    strength: '5-325',
    strengthUnit: 'mg',
    manufacturer: 'Mallinckrodt',
    isGeneric: true,
    isControlled: true,
    controlledSchedule: 'II',
    formularyStatus: 'non-preferred',
    therapeuticClass: 'Analgesics',
    pharmacologicClass: 'Opioid Combinations',
    warnings: ['Risk of addiction', 'Respiratory depression', 'Hepatotoxicity from acetaminophen'],
    contraindications: ['Respiratory depression', 'Acute/severe asthma', 'GI obstruction'],
  },
  {
    id: 'med-007',
    name: 'Sertraline',
    genericName: 'Sertraline Hydrochloride',
    brandNames: ['Zoloft'],
    ndc: '00049-4900-66',
    rxcui: '36437',
    form: 'tablet',
    strength: '50',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Central Nervous System Agents',
    pharmacologicClass: 'Selective Serotonin Reuptake Inhibitors (SSRIs)',
    warnings: ['Black box warning for suicidal thoughts in young adults', 'Serotonin syndrome risk'],
    contraindications: ['MAOIs within 14 days', 'Pimozide use'],
  },
  {
    id: 'med-008',
    name: 'Levothyroxine',
    genericName: 'Levothyroxine Sodium',
    brandNames: ['Synthroid', 'Levoxyl'],
    ndc: '00074-6582-90',
    rxcui: '966247',
    form: 'tablet',
    strength: '100',
    strengthUnit: 'mcg',
    manufacturer: 'AbbVie',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Hormones',
    pharmacologicClass: 'Thyroid Agents',
    warnings: ['Narrow therapeutic index', 'Take on empty stomach'],
    contraindications: ['Uncorrected adrenal insufficiency', 'Acute MI'],
  },
  {
    id: 'med-009',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    brandNames: ['Amoxil'],
    ndc: '00093-4150-01',
    rxcui: '723',
    form: 'capsule',
    strength: '500',
    strengthUnit: 'mg',
    manufacturer: 'Teva Pharmaceuticals',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Anti-Infectives',
    pharmacologicClass: 'Aminopenicillins',
    warnings: ['Risk of C. diff colitis', 'May cause allergic reactions'],
    contraindications: ['Penicillin allergy'],
  },
  {
    id: 'med-010',
    name: 'Albuterol',
    genericName: 'Albuterol Sulfate',
    brandNames: ['ProAir HFA', 'Ventolin HFA', 'Proventil HFA'],
    ndc: '59310-0579-22',
    rxcui: '745679',
    form: 'inhaler',
    strength: '90',
    strengthUnit: 'mcg/actuation',
    manufacturer: 'Teva',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Respiratory Agents',
    pharmacologicClass: 'Short-Acting Beta2 Agonists',
    warnings: ['Paradoxical bronchospasm', 'Cardiovascular effects'],
    contraindications: [],
  },
  {
    id: 'med-011',
    name: 'Alprazolam',
    genericName: 'Alprazolam',
    brandNames: ['Xanax'],
    ndc: '00009-0029-01',
    rxcui: '596',
    form: 'tablet',
    strength: '0.5',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: true,
    controlledSchedule: 'IV',
    formularyStatus: 'non-preferred',
    therapeuticClass: 'Central Nervous System Agents',
    pharmacologicClass: 'Benzodiazepines',
    warnings: ['Risk of dependence', 'CNS depression', 'Withdrawal symptoms'],
    contraindications: ['Acute narrow-angle glaucoma', 'Concurrent ketoconazole/itraconazole'],
  },
  {
    id: 'med-012',
    name: 'Gabapentin',
    genericName: 'Gabapentin',
    brandNames: ['Neurontin'],
    ndc: '00071-0806-24',
    rxcui: '25480',
    form: 'capsule',
    strength: '300',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Central Nervous System Agents',
    pharmacologicClass: 'Anticonvulsants',
    warnings: ['Respiratory depression with opioids', 'CNS depression'],
    contraindications: [],
  },
];

// Mock pharmacies
export const MOCK_PHARMACIES: Pharmacy[] = [
  {
    id: 'pharm-001',
    name: 'CVS Pharmacy #4521',
    address: '123 Main Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    phone: '(217) 555-0100',
    fax: '(217) 555-0101',
    ncpdpId: '1234567',
    npi: '1234567890',
    isRetail: true,
    isMailOrder: false,
    isSpecialty: false,
    is24Hour: true,
  },
  {
    id: 'pharm-002',
    name: 'Walgreens #5892',
    address: '456 Oak Avenue',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    phone: '(217) 555-0200',
    fax: '(217) 555-0201',
    ncpdpId: '2345678',
    npi: '2345678901',
    isRetail: true,
    isMailOrder: false,
    isSpecialty: false,
    is24Hour: false,
  },
  {
    id: 'pharm-003',
    name: 'Express Scripts Mail Order',
    address: '1 Express Way',
    city: 'St. Louis',
    state: 'MO',
    zip: '63102',
    phone: '(800) 555-0300',
    fax: '(800) 555-0301',
    ncpdpId: '3456789',
    npi: '3456789012',
    isRetail: false,
    isMailOrder: true,
    isSpecialty: false,
  },
  {
    id: 'pharm-004',
    name: 'Specialty Rx Center',
    address: '789 Medical Plaza',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    phone: '(312) 555-0400',
    fax: '(312) 555-0401',
    ncpdpId: '4567890',
    npi: '4567890123',
    isRetail: false,
    isMailOrder: true,
    isSpecialty: true,
  },
];

// Calculate dates
const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const lastWeek = new Date(today);
lastWeek.setDate(lastWeek.getDate() - 7);
const lastMonth = new Date(today);
lastMonth.setMonth(lastMonth.getMonth() - 1);
const threeMonthsAgo = new Date(today);
threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
const sixMonthsAgo = new Date(today);
sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);

// Mock prescriptions
export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-001',
    status: 'active',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[0], // Lisinopril
    patient: {
      id: 'pat-001',
      name: 'John Smith',
      dob: '1965-03-15',
      mrn: 'MRN-001234',
      allergies: ['Penicillin', 'Sulfa'],
    },
    prescriber: {
      id: 'prov-001',
      name: 'Dr. Sarah Johnson',
      npi: '1234567890',
      deaNumber: 'AJ1234567',
      specialty: 'Internal Medicine',
    },
    encounterId: 'enc-001',
    dosage: {
      text: 'Take 1 tablet by mouth once daily',
      timing: {
        frequency: 1,
        period: 1,
        periodUnit: 'd',
        when: ['MORN'],
        text: 'Once daily in the morning',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
    },
    dispense: {
      quantity: 30,
      unit: 'tablets',
      daysSupply: 30,
      refills: 5,
      refillsRemaining: 4,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[0],
    },
    reasonCode: 'I10',
    reasonDescription: 'Essential (primary) hypertension',
    indication: 'Hypertension management',
    authoredOn: lastMonth,
    validFrom: lastMonth,
    validUntil: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
    ePrescribeStatus: 'filled',
    ePrescribeSentAt: lastMonth,
    ePrescribeConfirmation: 'ERX-2024-001234',
    notes: 'Patient tolerating well. Monitor potassium levels.',
    patientInstructions: 'Take in the morning with or without food. Report any swelling or persistent cough.',
    createdAt: lastMonth,
    createdBy: 'prov-001',
    refillHistory: [
      {
        id: 'ref-001',
        refillNumber: 1,
        requestedAt: lastWeek,
        filledAt: new Date(lastWeek.getTime() + 86400000),
        pharmacy: MOCK_PHARMACIES[0],
        quantity: 30,
        daysSupply: 30,
        status: 'filled',
      },
    ],
  },
  {
    id: 'rx-002',
    status: 'active',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[1], // Metformin
    patient: {
      id: 'pat-001',
      name: 'John Smith',
      dob: '1965-03-15',
      mrn: 'MRN-001234',
      allergies: ['Penicillin', 'Sulfa'],
    },
    prescriber: {
      id: 'prov-001',
      name: 'Dr. Sarah Johnson',
      npi: '1234567890',
      deaNumber: 'AJ1234567',
      specialty: 'Internal Medicine',
    },
    encounterId: 'enc-001',
    dosage: {
      text: 'Take 1 tablet by mouth twice daily with meals',
      timing: {
        frequency: 2,
        period: 1,
        periodUnit: 'd',
        when: ['CM', 'CV'], // With breakfast and dinner
        text: 'Twice daily with meals',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
    },
    dispense: {
      quantity: 60,
      unit: 'tablets',
      daysSupply: 30,
      refills: 11,
      refillsRemaining: 9,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[0],
    },
    reasonCode: 'E11.9',
    reasonDescription: 'Type 2 diabetes mellitus without complications',
    indication: 'Diabetes management',
    authoredOn: threeMonthsAgo,
    validFrom: threeMonthsAgo,
    validUntil: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
    ePrescribeStatus: 'filled',
    ePrescribeSentAt: threeMonthsAgo,
    ePrescribeConfirmation: 'ERX-2024-001235',
    notes: 'A1c improved from 8.2 to 7.4. Continue current dose.',
    patientInstructions: 'Take with meals to reduce stomach upset. Stay hydrated.',
    createdAt: threeMonthsAgo,
    createdBy: 'prov-001',
    refillHistory: [
      {
        id: 'ref-002',
        refillNumber: 1,
        requestedAt: new Date(threeMonthsAgo.getTime() + 30 * 86400000),
        filledAt: new Date(threeMonthsAgo.getTime() + 31 * 86400000),
        pharmacy: MOCK_PHARMACIES[0],
        quantity: 60,
        daysSupply: 30,
        status: 'filled',
      },
      {
        id: 'ref-003',
        refillNumber: 2,
        requestedAt: lastMonth,
        filledAt: new Date(lastMonth.getTime() + 86400000),
        pharmacy: MOCK_PHARMACIES[0],
        quantity: 60,
        daysSupply: 30,
        status: 'filled',
      },
    ],
  },
  {
    id: 'rx-003',
    status: 'active',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[2], // Atorvastatin
    patient: {
      id: 'pat-002',
      name: 'Maria Garcia',
      dob: '1958-07-22',
      mrn: 'MRN-001235',
      allergies: [],
    },
    prescriber: {
      id: 'prov-002',
      name: 'Dr. Michael Chen',
      npi: '2345678901',
      deaNumber: 'BC2345678',
      specialty: 'Cardiology',
    },
    encounterId: 'enc-002',
    dosage: {
      text: 'Take 1 tablet by mouth at bedtime',
      timing: {
        frequency: 1,
        period: 1,
        periodUnit: 'd',
        when: ['HS'], // At bedtime
        text: 'Once daily at bedtime',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
    },
    dispense: {
      quantity: 90,
      unit: 'tablets',
      daysSupply: 90,
      refills: 3,
      refillsRemaining: 2,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[2], // Mail order
    },
    reasonCode: 'E78.5',
    reasonDescription: 'Hyperlipidemia, unspecified',
    indication: 'Hyperlipidemia management and cardiovascular risk reduction',
    authoredOn: sixMonthsAgo,
    validFrom: sixMonthsAgo,
    validUntil: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
    ePrescribeStatus: 'filled',
    ePrescribeSentAt: sixMonthsAgo,
    ePrescribeConfirmation: 'ERX-2024-001236',
    notes: 'LDL reduced from 165 to 98. Goal < 100.',
    patientInstructions: 'Take at bedtime. Avoid grapefruit juice. Report muscle pain immediately.',
    createdAt: sixMonthsAgo,
    createdBy: 'prov-002',
    refillHistory: [
      {
        id: 'ref-004',
        refillNumber: 1,
        requestedAt: threeMonthsAgo,
        filledAt: new Date(threeMonthsAgo.getTime() + 3 * 86400000),
        pharmacy: MOCK_PHARMACIES[2],
        quantity: 90,
        daysSupply: 90,
        status: 'filled',
      },
    ],
  },
  {
    id: 'rx-004',
    status: 'active',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[5], // Hydrocodone-Acetaminophen
    patient: {
      id: 'pat-003',
      name: 'Robert Wilson',
      dob: '1972-11-08',
      mrn: 'MRN-001236',
      allergies: ['Codeine'],
    },
    prescriber: {
      id: 'prov-003',
      name: 'Dr. Emily Rodriguez',
      npi: '3456789012',
      deaNumber: 'FR3456789',
      specialty: 'Orthopedic Surgery',
    },
    encounterId: 'enc-003',
    dosage: {
      text: 'Take 1-2 tablets by mouth every 6 hours as needed for pain',
      timing: {
        frequency: 1,
        period: 6,
        periodUnit: 'h',
        text: 'Every 6 hours as needed',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
      maxDosePerPeriod: '8 tablets per day',
      asNeeded: true,
      asNeededReason: 'Pain',
    },
    dispense: {
      quantity: 30,
      unit: 'tablets',
      daysSupply: 7,
      refills: 0,
      refillsRemaining: 0,
      substitutionsAllowed: false,
      dispenseAsWritten: true,
      pharmacy: MOCK_PHARMACIES[0],
    },
    reasonCode: 'M54.5',
    reasonDescription: 'Low back pain',
    indication: 'Acute post-operative pain management',
    authoredOn: yesterday,
    validFrom: yesterday,
    validUntil: new Date(today.getTime() + 30 * 86400000),
    ePrescribeStatus: 'sent',
    ePrescribeSentAt: yesterday,
    ePrescribeConfirmation: 'ERX-2024-001237',
    notes: 'Post-operative pain control. Short-term use only. Patient counseled on risks.',
    pharmacyNotes: 'Patient ID verified. DEA requirements met.',
    patientInstructions: 'Do not drive or operate machinery. Do not combine with alcohol. Dispose of unused medication safely.',
    createdAt: yesterday,
    createdBy: 'prov-003',
  },
  {
    id: 'rx-005',
    status: 'draft',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[6], // Sertraline
    patient: {
      id: 'pat-004',
      name: 'Emily Thompson',
      dob: '1990-04-12',
      mrn: 'MRN-001237',
      allergies: [],
    },
    prescriber: {
      id: 'prov-004',
      name: 'Dr. James Park',
      npi: '4567890123',
      deaNumber: 'BP4567890',
      specialty: 'Psychiatry',
    },
    encounterId: 'enc-004',
    dosage: {
      text: 'Take 1 tablet by mouth once daily',
      timing: {
        frequency: 1,
        period: 1,
        periodUnit: 'd',
        when: ['MORN'],
        text: 'Once daily in the morning',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
    },
    dispense: {
      quantity: 30,
      unit: 'tablets',
      daysSupply: 30,
      refills: 2,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[1],
    },
    reasonCode: 'F32.1',
    reasonDescription: 'Major depressive disorder, single episode, moderate',
    indication: 'Depression',
    authoredOn: today,
    notes: 'Starting dose. Plan to increase to 100mg after 4 weeks if tolerated.',
    patientInstructions: 'May take 4-6 weeks to see full benefit. Do not stop suddenly.',
    createdAt: today,
    createdBy: 'prov-004',
  },
  {
    id: 'rx-006',
    status: 'completed',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[8], // Amoxicillin
    patient: {
      id: 'pat-005',
      name: 'David Lee',
      dob: '1985-09-30',
      mrn: 'MRN-001238',
      allergies: [],
    },
    prescriber: {
      id: 'prov-001',
      name: 'Dr. Sarah Johnson',
      npi: '1234567890',
      deaNumber: 'AJ1234567',
      specialty: 'Internal Medicine',
    },
    encounterId: 'enc-005',
    dosage: {
      text: 'Take 1 capsule by mouth three times daily for 10 days',
      timing: {
        frequency: 3,
        period: 1,
        periodUnit: 'd',
        duration: 10,
        durationUnit: 'd',
        text: 'Three times daily for 10 days',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'capsule',
    },
    dispense: {
      quantity: 30,
      unit: 'capsules',
      daysSupply: 10,
      refills: 0,
      refillsRemaining: 0,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[1],
    },
    reasonCode: 'J02.9',
    reasonDescription: 'Acute pharyngitis, unspecified',
    indication: 'Strep throat',
    authoredOn: lastWeek,
    validFrom: lastWeek,
    validUntil: new Date(lastWeek.getTime() + 30 * 86400000),
    ePrescribeStatus: 'filled',
    ePrescribeSentAt: lastWeek,
    ePrescribeConfirmation: 'ERX-2024-001238',
    notes: 'Positive rapid strep test. Complete full course.',
    patientInstructions: 'Complete all medication even if feeling better. Take with or without food.',
    createdAt: lastWeek,
    createdBy: 'prov-001',
  },
  {
    id: 'rx-007',
    status: 'on-hold',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[1], // Metformin
    patient: {
      id: 'pat-006',
      name: 'Susan Martinez',
      dob: '1968-12-05',
      mrn: 'MRN-001239',
      allergies: ['Iodine contrast'],
    },
    prescriber: {
      id: 'prov-001',
      name: 'Dr. Sarah Johnson',
      npi: '1234567890',
      deaNumber: 'AJ1234567',
      specialty: 'Internal Medicine',
    },
    encounterId: 'enc-006',
    dosage: {
      text: 'Take 1 tablet by mouth twice daily with meals',
      timing: {
        frequency: 2,
        period: 1,
        periodUnit: 'd',
        when: ['CM', 'CV'],
        text: 'Twice daily with meals',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
    },
    dispense: {
      quantity: 60,
      unit: 'tablets',
      daysSupply: 30,
      refills: 5,
      refillsRemaining: 3,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[0],
    },
    reasonCode: 'E11.9',
    reasonDescription: 'Type 2 diabetes mellitus without complications',
    indication: 'Diabetes management',
    authoredOn: threeMonthsAgo,
    validFrom: threeMonthsAgo,
    validUntil: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
    ePrescribeStatus: 'filled',
    notes: 'ON HOLD - Patient scheduled for CT with contrast on 1/5. Resume 48 hours after procedure.',
    patientInstructions: 'Do not take until cleared by your doctor after CT scan.',
    createdAt: threeMonthsAgo,
    createdBy: 'prov-001',
    updatedAt: yesterday,
    updatedBy: 'prov-001',
  },
  {
    id: 'rx-008',
    status: 'cancelled',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[10], // Alprazolam
    patient: {
      id: 'pat-007',
      name: 'Michael Brown',
      dob: '1982-06-18',
      mrn: 'MRN-001240',
      allergies: [],
    },
    prescriber: {
      id: 'prov-004',
      name: 'Dr. James Park',
      npi: '4567890123',
      deaNumber: 'BP4567890',
      specialty: 'Psychiatry',
    },
    dosage: {
      text: 'Take 1 tablet by mouth three times daily as needed for anxiety',
      timing: {
        frequency: 3,
        period: 1,
        periodUnit: 'd',
        text: 'Three times daily as needed',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
      asNeeded: true,
      asNeededReason: 'Anxiety',
    },
    dispense: {
      quantity: 30,
      unit: 'tablets',
      daysSupply: 10,
      refills: 0,
      refillsRemaining: 0,
      substitutionsAllowed: false,
      dispenseAsWritten: true,
      pharmacy: MOCK_PHARMACIES[0],
    },
    reasonCode: 'F41.1',
    reasonDescription: 'Generalized anxiety disorder',
    indication: 'Anxiety',
    authoredOn: lastWeek,
    notes: 'CANCELLED - Patient reported previous substance use disorder not disclosed initially.',
    createdAt: lastWeek,
    createdBy: 'prov-004',
    updatedAt: yesterday,
    updatedBy: 'prov-004',
  },
  {
    id: 'rx-009',
    status: 'active',
    intent: 'order',
    priority: 'routine',
    medication: MOCK_MEDICATIONS[9], // Albuterol
    patient: {
      id: 'pat-008',
      name: 'Jennifer Adams',
      dob: '1995-02-28',
      mrn: 'MRN-001241',
      allergies: ['Aspirin'],
    },
    prescriber: {
      id: 'prov-005',
      name: 'Dr. Lisa Wang',
      npi: '5678901234',
      deaNumber: 'AW5678901',
      specialty: 'Pulmonology',
    },
    encounterId: 'enc-007',
    dosage: {
      text: '2 puffs inhaled every 4-6 hours as needed for shortness of breath or wheezing',
      timing: {
        frequency: 1,
        period: 4,
        periodUnit: 'h',
        text: 'Every 4-6 hours as needed',
      },
      route: 'inhalation',
      doseQuantity: 2,
      doseUnit: 'puffs',
      asNeeded: true,
      asNeededReason: 'Shortness of breath or wheezing',
    },
    dispense: {
      quantity: 1,
      unit: 'inhaler (200 actuations)',
      daysSupply: 30,
      refills: 11,
      refillsRemaining: 10,
      substitutionsAllowed: true,
      pharmacy: MOCK_PHARMACIES[0],
    },
    reasonCode: 'J45.20',
    reasonDescription: 'Mild intermittent asthma, uncomplicated',
    indication: 'Asthma rescue medication',
    authoredOn: lastMonth,
    validFrom: lastMonth,
    validUntil: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
    ePrescribeStatus: 'filled',
    ePrescribeSentAt: lastMonth,
    ePrescribeConfirmation: 'ERX-2024-001240',
    notes: 'Using about 2-3 times per week. If increasing frequency, add controller medication.',
    patientInstructions: 'Shake well before use. Wait 1 minute between puffs. Rinse mouth after use.',
    createdAt: lastMonth,
    createdBy: 'prov-005',
  },
  {
    id: 'rx-010',
    status: 'active',
    intent: 'order',
    priority: 'urgent',
    medication: MOCK_MEDICATIONS[7], // Levothyroxine
    patient: {
      id: 'pat-009',
      name: 'Patricia Johnson',
      dob: '1970-08-14',
      mrn: 'MRN-001242',
      allergies: [],
    },
    prescriber: {
      id: 'prov-006',
      name: 'Dr. Andrew Miller',
      npi: '6789012345',
      deaNumber: 'AM6789012',
      specialty: 'Endocrinology',
    },
    encounterId: 'enc-008',
    dosage: {
      text: 'Take 1 tablet by mouth once daily on an empty stomach',
      timing: {
        frequency: 1,
        period: 1,
        periodUnit: 'd',
        when: ['MORN.early'],
        text: 'Once daily, 30-60 minutes before breakfast',
      },
      route: 'oral',
      doseQuantity: 1,
      doseUnit: 'tablet',
    },
    dispense: {
      quantity: 90,
      unit: 'tablets',
      daysSupply: 90,
      refills: 3,
      refillsRemaining: 3,
      substitutionsAllowed: false,
      dispenseAsWritten: true,
      pharmacy: MOCK_PHARMACIES[2],
    },
    reasonCode: 'E03.9',
    reasonDescription: 'Hypothyroidism, unspecified',
    indication: 'Hypothyroidism',
    authoredOn: today,
    validFrom: today,
    validUntil: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
    ePrescribeStatus: 'sent',
    ePrescribeSentAt: today,
    priorAuthRequired: false,
    notes: 'Dose increased from 75mcg due to elevated TSH (6.8). Recheck TSH in 6 weeks.',
    patientInstructions: 'Take on empty stomach, 30-60 minutes before breakfast. Separate from calcium and iron supplements by 4 hours.',
    createdAt: today,
    createdBy: 'prov-006',
  },
];

// Formulary entries for the medications
export const MOCK_FORMULARY: FormularyEntry[] = MOCK_MEDICATIONS.map((med, index) => ({
  medication: med,
  tierLevel: med.isGeneric ? (index % 2 === 0 ? 1 : 2) : 3 as 1 | 2 | 3,
  copay: med.isGeneric ? (index % 2 === 0 ? 10 : 20) : 50,
  requiresPriorAuth: med.requiresPriorAuth || false,
  quantityLimit: med.isControlled ? 30 : undefined,
  quantityLimitPeriod: med.isControlled ? 'd' as const : undefined,
  stepTherapyRequired: false,
  specialtyDrug: false,
  effectiveDate: new Date('2024-01-01'),
}));

// Drug interactions
export const MOCK_DRUG_INTERACTIONS: DrugInteraction[] = [
  {
    drugId: 'med-001', // Lisinopril
    drugName: 'Potassium supplements',
    severity: 'moderate',
    description: 'ACE inhibitors can increase serum potassium levels',
    clinicalSignificance: 'Monitor potassium levels when starting or adjusting potassium supplements',
  },
  {
    drugId: 'med-006', // Hydrocodone
    drugName: 'Alprazolam',
    severity: 'high',
    description: 'Concurrent use of opioids and benzodiazepines increases risk of respiratory depression',
    clinicalSignificance: 'Avoid combination if possible. If necessary, use lowest effective doses.',
  },
  {
    drugId: 'med-007', // Sertraline
    drugName: 'MAO inhibitors',
    severity: 'high',
    description: 'Risk of serotonin syndrome',
    clinicalSignificance: 'Contraindicated. Wait 14 days between discontinuing MAOI and starting sertraline.',
  },
  {
    drugId: 'med-002', // Metformin
    drugName: 'Iodinated contrast',
    severity: 'moderate',
    description: 'Risk of contrast-induced nephropathy and lactic acidosis',
    clinicalSignificance: 'Hold metformin before and 48 hours after contrast procedures.',
  },
];
