import { 
  Prescription, 
  Medication, 
  Pharmacy, 
  FormularyEntry,
  DrugInteraction 
} from '../../models/prescription.model';

// Common medications database
export const MOCK_MEDICATIONS: Medication[] = [
  {
    id: 'med-001',
    name: 'Lisinopril',
    genericName: 'Lisinopril',
    brandNames: ['Prinivil', 'Zestril'],
    ndc: '00093-7180-01',
    rxcui: '104377',
    form: 'tablet',
    strength: '10',
    strengthUnit: 'mg',
    manufacturer: 'Teva Pharmaceuticals',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Cardiovascular Agents',
    pharmacologicClass: 'ACE Inhibitors',
    warnings: ['May cause persistent cough', 'Risk of angioedema'],
    contraindications: ['Pregnancy', 'History of angioedema with ACE inhibitors'],
  },
  {
    id: 'med-002',
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride',
    brandNames: ['Glucophage', 'Fortamet'],
    ndc: '00591-0584-01',
    rxcui: '6809',
    form: 'tablet',
    strength: '500',
    strengthUnit: 'mg',
    manufacturer: 'Mylan Pharmaceuticals',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Metabolic Agents',
    pharmacologicClass: 'Biguanides',
    warnings: ['Risk of lactic acidosis', 'Hold before contrast procedures'],
    contraindications: ['Renal impairment (eGFR <30)', 'Metabolic acidosis'],
  },
  {
    id: 'med-003',
    name: 'Atorvastatin',
    genericName: 'Atorvastatin Calcium',
    brandNames: ['Lipitor'],
    ndc: '00071-0155-23',
    rxcui: '617314',
    form: 'tablet',
    strength: '20',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Cardiovascular Agents',
    pharmacologicClass: 'HMG-CoA Reductase Inhibitors (Statins)',
    warnings: ['Risk of myopathy/rhabdomyolysis', 'Monitor liver function'],
    contraindications: ['Active liver disease', 'Pregnancy'],
  },
  {
    id: 'med-004',
    name: 'Omeprazole',
    genericName: 'Omeprazole',
    brandNames: ['Prilosec'],
    ndc: '00186-5020-31',
    rxcui: '7646',
    form: 'capsule',
    strength: '20',
    strengthUnit: 'mg',
    manufacturer: 'AstraZeneca',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Gastrointestinal Agents',
    pharmacologicClass: 'Proton Pump Inhibitors',
    warnings: ['Long-term use may increase fracture risk', 'May mask gastric cancer symptoms'],
    contraindications: [],
  },
  {
    id: 'med-005',
    name: 'Amlodipine',
    genericName: 'Amlodipine Besylate',
    brandNames: ['Norvasc'],
    ndc: '00069-1520-30',
    rxcui: '17767',
    form: 'tablet',
    strength: '5',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Cardiovascular Agents',
    pharmacologicClass: 'Calcium Channel Blockers',
    warnings: ['May cause peripheral edema', 'May worsen angina on initiation'],
    contraindications: [],
  },
  {
    id: 'med-006',
    name: 'Hydrocodone-Acetaminophen',
    genericName: 'Hydrocodone Bitartrate and Acetaminophen',
    brandNames: ['Vicodin', 'Norco', 'Lortab'],
    ndc: '00591-0385-01',
    rxcui: '857001',
    form: 'tablet',
    strength: '5-325',
    strengthUnit: 'mg',
    manufacturer: 'Mallinckrodt',
    isGeneric: true,
    isControlled: true,
    controlledSchedule: 'II',
    formularyStatus: 'non-preferred',
    therapeuticClass: 'Analgesics',
    pharmacologicClass: 'Opioid Combinations',
    warnings: ['Risk of addiction', 'Respiratory depression', 'Hepatotoxicity from acetaminophen'],
    contraindications: ['Respiratory depression', 'Acute/severe asthma', 'GI obstruction'],
  },
  {
    id: 'med-007',
    name: 'Sertraline',
    genericName: 'Sertraline Hydrochloride',
    brandNames: ['Zoloft'],
    ndc: '00049-4900-66',
    rxcui: '36437',
    form: 'tablet',
    strength: '50',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Central Nervous System Agents',
    pharmacologicClass: 'Selective Serotonin Reuptake Inhibitors (SSRIs)',
    warnings: ['Black box warning for suicidal thoughts in young adults', 'Serotonin syndrome risk'],
    contraindications: ['MAOIs within 14 days', 'Pimozide use'],
  },
  {
    id: 'med-008',
    name: 'Levothyroxine',
    genericName: 'Levothyroxine Sodium',
    brandNames: ['Synthroid', 'Levoxyl'],
    ndc: '00074-6582-90',
    rxcui: '966247',
    form: 'tablet',
    strength: '100',
    strengthUnit: 'mcg',
    manufacturer: 'AbbVie',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Hormones',
    pharmacologicClass: 'Thyroid Agents',
    warnings: ['Narrow therapeutic index', 'Take on empty stomach'],
    contraindications: ['Uncorrected adrenal insufficiency', 'Acute MI'],
  },
  {
    id: 'med-009',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    brandNames: ['Amoxil'],
    ndc: '00093-4150-01',
    rxcui: '723',
    form: 'capsule',
    strength: '500',
    strengthUnit: 'mg',
    manufacturer: 'Teva Pharmaceuticals',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Anti-Infectives',
    pharmacologicClass: 'Aminopenicillins',
    warnings: ['Risk of C. diff colitis', 'May cause allergic reactions'],
    contraindications: ['Penicillin allergy'],
  },
  {
    id: 'med-010',
    name: 'Albuterol',
    genericName: 'Albuterol Sulfate',
    brandNames: ['ProAir HFA', 'Ventolin HFA', 'Proventil HFA'],
    ndc: '59310-0579-22',
    rxcui: '745679',
    form: 'inhaler',
    strength: '90',
    strengthUnit: 'mcg/actuation',
    manufacturer: 'Teva',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Respiratory Agents',
    pharmacologicClass: 'Short-Acting Beta2 Agonists',
    warnings: ['Paradoxical bronchospasm', 'Cardiovascular effects'],
    contraindications: [],
  },
  {
    id: 'med-011',
    name: 'Alprazolam',
    genericName: 'Alprazolam',
    brandNames: ['Xanax'],
    ndc: '00009-0029-01',
    rxcui: '596',
    form: 'tablet',
    strength: '0.5',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: true,
    controlledSchedule: 'IV',
    formularyStatus: 'non-preferred',
    therapeuticClass: 'Central Nervous System Agents',
    pharmacologicClass: 'Benzodiazepines',
    warnings: ['Risk of dependence', 'CNS depression', 'Withdrawal symptoms'],
    contraindications: ['Acute narrow-angle glaucoma', 'Concurrent ketoconazole/itraconazole'],
  },
  {
    id: 'med-012',
    name: 'Gabapentin',
    genericName: 'Gabapentin',
    brandNames: ['Neurontin'],
    ndc: '00071-0806-24',
    rxcui: '25480',
    form: 'capsule',
    strength: '300',
    strengthUnit: 'mg',
    manufacturer: 'Pfizer',
    isGeneric: true,
    isControlled: false,
    formularyStatus: 'preferred',
    therapeuticClass: 'Central Nervous System Agents',
    pharmacologicClass: 'Anticonvulsants',
    warnings: ['Respiratory depression with opioids', 'CNS depression'],
    contraindications: [],
  },
];

// Mock pharmacies
export const MOCK_PHARMACIES: Pharmacy[] = [
  {
    id: 'pharm-001',
    name: 'CVS Pharmacy #4521',
    address: '123 Main Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    phone: '(217) 555-0100',
    fax: '(217) 555-0101',
    ncpdpId: '1234567',
    npi: '1234567890',
    isRetail: true,
    isMailOrder: false,
    isSpecialty: false,
    is24Hour: true,
  },
  {
    id: 'pharm-002',
    name: 'Walgreens #5892',
    address: '456 Oak Avenue',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    phone: '(217) 555-0200',
    fax: '(217) 555-0201',
    ncpdpId: '2345678',
    npi: '2345678901',
    isRetail: true,
    isMailOrder: false,
    isSpecialty: false,
    is24Hour: false,
  },
  {
    id: 'pharm-003',
    name: 'Express Scripts Mail Order',
    address: '1 Express Way',
    city: 'St. Louis',
    state: 'MO',
    zip: '63102',
    phone: '(800) 555-0300',
    fax: '(800) 555-0301',
    ncpdpId: '3456789',
    npi: '3456789012',
    isRetail: false,
    isMailOrder: true,
    isSpecialty: false,
  },
  {
    id: 'pharm-004',
    name: 'Specialty Rx Center',
    address: '789 Medical Plaza',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    phone: '(312) 555-0400',
    fax: '(312) 555-0401',
    ncpdpId: '4567890',
    npi: '4567890123',
    isRetail: false,
    isMailOrder: true,
    isSpecialty: true,
  },
];

// Calculate dates
const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const lastWeek = new Date(today);
lastWeek.setDate(lastWeek.getDate() - 7);
const lastMonth = new Date(today);
lastMonth.setMonth(lastMonth.getMonth() - 1);
const threeMonthsAgo = new Date(today);
threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
const sixMonthsAgo = new Date(today);
sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);

// Mock prescriptions
export const MOCK_PRESCRIPTIONS: Prescription[] = [];

// Formulary entries for the medications
export const MOCK_FORMULARY: FormularyEntry[] = MOCK_MEDICATIONS.map((med, index) => ({
  medication: med,
  tierLevel: med.isGeneric ? (index % 2 === 0 ? 1 : 2) : 3 as 1 | 2 | 3,
  copay: med.isGeneric ? (index % 2 === 0 ? 10 : 20) : 50,
  requiresPriorAuth: med.requiresPriorAuth || false,
  quantityLimit: med.isControlled ? 30 : undefined,
  quantityLimitPeriod: med.isControlled ? 'd' as const : undefined,
  stepTherapyRequired: false,
  specialtyDrug: false,
  effectiveDate: new Date('2024-01-01'),
}));

// Drug interactions
export const MOCK_DRUG_INTERACTIONS: DrugInteraction[] = [
  {
    drugId: 'med-001', // Lisinopril
    drugName: 'Potassium supplements',
    severity: 'moderate',
    description: 'ACE inhibitors can increase serum potassium levels',
    clinicalSignificance: 'Monitor potassium levels when starting or adjusting potassium supplements',
  },
  {
    drugId: 'med-006', // Hydrocodone
    drugName: 'Alprazolam',
    severity: 'high',
    description: 'Concurrent use of opioids and benzodiazepines increases risk of respiratory depression',
    clinicalSignificance: 'Avoid combination if possible. If necessary, use lowest effective doses.',
  },
  {
    drugId: 'med-007', // Sertraline
    drugName: 'MAO inhibitors',
    severity: 'high',
    description: 'Risk of serotonin syndrome',
    clinicalSignificance: 'Contraindicated. Wait 14 days between discontinuing MAOI and starting sertraline.',
  },
  {
    drugId: 'med-002', // Metformin
    drugName: 'Iodinated contrast',
    severity: 'moderate',
    description: 'Risk of contrast-induced nephropathy and lactic acidosis',
    clinicalSignificance: 'Hold metformin before and 48 hours after contrast procedures.',
  },
];
