import { Patient, PatientSummary } from '../../models/patient.model';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    mrn: 'MRN00001234',
    status: 'active',
    firstName: 'John',
    middleName: 'Michael',
    lastName: 'Smith',
    dateOfBirth: new Date('1985-03-15'),
    gender: 'male',
    email: 'john.smith@email.com',
    phone: '(555) 123-4567',
    mobilePhone: '(555) 987-6543',
    preferredContactMethod: 'phone',
    address: {
      line1: '123 Main Street',
      line2: 'Apt 4B',
      city: 'Springfield',
      state: 'IL',
      postalCode: '62701',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Jane Smith',
      relationship: 'Spouse',
      phone: '(555) 234-5678',
    },
    insurances: [
      {
        id: 'ins-001',
        type: 'primary',
        payerId: 'BCBS001',
        payerName: 'Blue Cross Blue Shield',
        planName: 'PPO Gold',
        memberId: 'BCBS123456789',
        groupNumber: 'GRP001',
        subscriberName: 'John Smith',
        subscriberRelationship: 'self',
        effectiveDate: new Date('2023-01-01'),
        copay: 25,
        deductible: 500,
      },
    ],
    primaryProviderId: 'prov-001',
    primaryProvider: {
      id: 'prov-001',
      name: 'Dr. Sarah Johnson',
      npi: '1234567890',
      specialty: 'Family Medicine',
    },
    allergies: [
      {
        id: 'alg-001',
        type: 'drug',
        allergen: 'Penicillin',
        reaction: 'Hives, difficulty breathing',
        severity: 'severe',
        status: 'active',
        recordedDate: new Date('2020-05-10'),
      },
      {
        id: 'alg-002',
        type: 'food',
        allergen: 'Peanuts',
        reaction: 'Anaphylaxis',
        severity: 'life-threatening',
        status: 'active',
        recordedDate: new Date('2019-01-15'),
      },
    ],
    problems: [
      {
        id: 'prob-001',
        code: 'E11.9',
        description: 'Type 2 Diabetes Mellitus without complications',
        status: 'active',
        onsetDate: new Date('2018-06-01'),
        clinicalStatus: 'active',
        verificationStatus: 'confirmed',
        severity: 'moderate',
      },
      {
        id: 'prob-002',
        code: 'I10',
        description: 'Essential Hypertension',
        status: 'active',
        onsetDate: new Date('2019-03-15'),
        clinicalStatus: 'active',
        verificationStatus: 'confirmed',
        severity: 'mild',
      },
    ],
    facilityId: 'fac-001',
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2024-12-01'),
    lastVisit: new Date('2024-11-15'),
    nextAppointment: new Date('2025-01-15'),
    consentStatus: {
      hipaaConsent: true,
      hipaaConsentDate: new Date('2020-01-01'),
      treatmentConsent: true,
      treatmentConsentDate: new Date('2020-01-01'),
      marketingConsent: false,
      portalConsent: true,
    },
    portalEnabled: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  },
  {
    id: 'pat-002',
    mrn: 'MRN00001235',
    status: 'active',
    firstName: 'Maria',
    lastName: 'Garcia',
    dateOfBirth: new Date('1992-07-22'),
    gender: 'female',
    email: 'maria.garcia@email.com',
    phone: '(555) 345-6789',
    preferredContactMethod: 'email',
    address: {
      line1: '456 Oak Avenue',
      city: 'Springfield',
      state: 'IL',
      postalCode: '62702',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Carlos Garcia',
      relationship: 'Brother',
      phone: '(555) 456-7890',
    },
    primaryProviderId: 'prov-002',
    primaryProvider: {
      id: 'prov-002',
      name: 'Dr. Michael Chen',
      npi: '2345678901',
      specialty: 'Internal Medicine',
    },
    allergies: [],
    problems: [
      {
        id: 'prob-003',
        code: 'J45.20',
        description: 'Mild intermittent asthma, uncomplicated',
        status: 'active',
        onsetDate: new Date('2010-01-01'),
        clinicalStatus: 'active',
        verificationStatus: 'confirmed',
        severity: 'mild',
      },
    ],
    facilityId: 'fac-001',
    createdAt: new Date('2021-03-15'),
    updatedAt: new Date('2024-10-20'),
    lastVisit: new Date('2024-10-20'),
    consentStatus: {
      hipaaConsent: true,
      hipaaConsentDate: new Date('2021-03-15'),
      treatmentConsent: true,
      treatmentConsentDate: new Date('2021-03-15'),
      marketingConsent: true,
      portalConsent: true,
    },
    portalEnabled: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  },
  {
    id: 'pat-003',
    mrn: 'MRN00001236',
    status: 'active',
    firstName: 'Robert',
    lastName: 'Johnson',
    dateOfBirth: new Date('1958-11-08'),
    gender: 'male',
    phone: '(555) 567-8901',
    preferredContactMethod: 'phone',
    address: {
      line1: '789 Elm Street',
      city: 'Springfield',
      state: 'IL',
      postalCode: '62703',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Linda Johnson',
      relationship: 'Wife',
      phone: '(555) 678-9012',
    },
    primaryProviderId: 'prov-001',
    allergies: [
      {
        id: 'alg-003',
        type: 'drug',
        allergen: 'Sulfa drugs',
        reaction: 'Rash',
        severity: 'moderate',
        status: 'active',
        recordedDate: new Date('2015-08-20'),
      },
    ],
    problems: [
      {
        id: 'prob-004',
        code: 'I25.10',
        description: 'Atherosclerotic heart disease',
        status: 'active',
        onsetDate: new Date('2020-02-01'),
        clinicalStatus: 'active',
        verificationStatus: 'confirmed',
        severity: 'severe',
      },
      {
        id: 'prob-005',
        code: 'E78.5',
        description: 'Hyperlipidemia, unspecified',
        status: 'active',
        onsetDate: new Date('2018-05-15'),
        clinicalStatus: 'active',
        verificationStatus: 'confirmed',
        severity: 'moderate',
      },
    ],
    facilityId: 'fac-001',
    createdAt: new Date('2019-06-01'),
    updatedAt: new Date('2024-11-30'),
    lastVisit: new Date('2024-11-30'),
    nextAppointment: new Date('2025-02-01'),
    consentStatus: {
      hipaaConsent: true,
      hipaaConsentDate: new Date('2019-06-01'),
      treatmentConsent: true,
      treatmentConsentDate: new Date('2019-06-01'),
      marketingConsent: false,
      portalConsent: false,
    },
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
  },
  {
    id: 'pat-004',
    mrn: 'MRN00001237',
    status: 'active',
    firstName: 'Emily',
    lastName: 'Williams',
    dateOfBirth: new Date('2015-04-12'),
    gender: 'female',
    phone: '(555) 789-0123',
    preferredContactMethod: 'phone',
    address: {
      line1: '321 Maple Drive',
      city: 'Springfield',
      state: 'IL',
      postalCode: '62704',
      country: 'USA',
    },
    emergencyContact: {
      name: 'Susan Williams',
      relationship: 'Mother',
      phone: '(555) 890-1234',
    },
    primaryProviderId: 'prov-003',
    primaryProvider: {
      id: 'prov-003',
      name: 'Dr. Lisa Anderson',
      npi: '3456789012',
      specialty: 'Pediatrics',
    },
    allergies: [],
    problems: [],
    facilityId: 'fac-001',
    createdAt: new Date('2022-05-01'),
    updatedAt: new Date('2024-09-15'),
    lastVisit: new Date('2024-09-15'),
    consentStatus: {
      hipaaConsent: true,
      hipaaConsentDate: new Date('2022-05-01'),
      treatmentConsent: true,
      treatmentConsentDate: new Date('2022-05-01'),
      marketingConsent: false,
      portalConsent: false,
    },
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
  },
  {
    id: 'pat-005',
    mrn: 'MRN00001238',
    status: 'active',
    firstName: 'James',
    lastName: 'Brown',
    dateOfBirth: new Date('1975-09-30'),
    gender: 'male',
    email: 'james.brown@email.com',
    phone: '(555) 901-2345',
    mobilePhone: '(555) 012-3456',
    preferredContactMethod: 'email',
    address: {
      line1: '654 Pine Road',
      city: 'Springfield',
      state: 'IL',
      postalCode: '62705',
      country: 'USA',
    },
    primaryProviderId: 'prov-002',
    allergies: [
      {
        id: 'alg-004',
        type: 'drug',
        allergen: 'Aspirin',
        reaction: 'GI upset',
        severity: 'mild',
        status: 'active',
        recordedDate: new Date('2022-01-10'),
      },
    ],
    problems: [
      {
        id: 'prob-006',
        code: 'F32.1',
        description: 'Major depressive disorder, single episode, moderate',
        status: 'active',
        onsetDate: new Date('2022-06-01'),
        clinicalStatus: 'active',
        verificationStatus: 'confirmed',
        severity: 'moderate',
      },
    ],
    facilityId: 'fac-001',
    createdAt: new Date('2021-08-15'),
    updatedAt: new Date('2024-12-05'),
    lastVisit: new Date('2024-12-05'),
    consentStatus: {
      hipaaConsent: true,
      hipaaConsentDate: new Date('2021-08-15'),
      treatmentConsent: true,
      treatmentConsentDate: new Date('2021-08-15'),
      marketingConsent: true,
      portalConsent: true,
    },
    portalEnabled: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
  },
];

// Generate patient summaries from full patient data
export const MOCK_PATIENT_SUMMARIES: PatientSummary[] = MOCK_PATIENTS.map(patient => ({
  id: patient.id,
  mrn: patient.mrn,
  fullName: `${patient.firstName} ${patient.lastName}`,
  dateOfBirth: patient.dateOfBirth,
  age: calculateAge(patient.dateOfBirth),
  gender: patient.gender,
  phone: patient.phone,
  lastVisit: patient.lastVisit,
  primaryProvider: patient.primaryProvider?.name,
  status: patient.status,
  photoUrl: patient.photoUrl,
}));

function calculateAge(dateOfBirth: Date): number {
  const today = new Date();
  const birthDate = new Date(dateOfBirth);
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDiff = today.getMonth() - birthDate.getMonth();
  
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  
  return age;
}
