import { RoundingSheet, RoundingSheetTemplate } from '../../models/rounding-sheet.model';

// ─── Template 1: General Medicine ────────────────────────────────────────────

export const MOCK_TEMPLATE_GENERAL_MED: RoundingSheetTemplate = {
  id: 'TPL-DEFAULT-001',
  name: 'General Medicine Rounding',
  description: 'Standard rounding sheet for general medicine floor',
  specialty: 'Internal Medicine',
  isDefault: true,
  isShared: true,
  createdBy: 'USR-001',
  createdByName: 'Dr. Sarah Wilson',
  createdAt: '2025-11-01T08:00:00Z',
  updatedAt: '2026-01-15T10:30:00Z',
  useCount: 142,
  lastUsedAt: '2026-02-19T07:45:00Z',
  tags: ['medicine', 'floor', 'general'],
  sections: [
    {
      id: 'SEC-GM-001',
      title: 'Patient Information',
      order: 0,
      isCollapsible: false,
      fields: [
        {
          id: 'FLD-GM-001',
          type: 'text',
          label: 'Room / Bed',
          columnSize: 'small',
          required: true,
          order: 0,
        },
        {
          id: 'FLD-GM-002',
          type: 'text',
          label: 'Primary Diagnosis',
          columnSize: 'large',
          required: true,
          order: 1,
        },
        {
          id: 'FLD-GM-003',
          type: 'number',
          label: 'Hospital Day #',
          columnSize: 'small',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-GM-004',
          type: 'text',
          label: 'Code Status',
          columnSize: 'medium',
          required: false,
          defaultValue: 'Full Code',
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-GM-002',
      title: 'Vitals',
      order: 1,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-GM-010',
          type: 'vital-sign',
          label: 'BP',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.bp',
          order: 0,
        },
        {
          id: 'FLD-GM-011',
          type: 'vital-sign',
          label: 'HR',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.hr',
          order: 1,
        },
        {
          id: 'FLD-GM-012',
          type: 'vital-sign',
          label: 'Temp',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.temp',
          order: 2,
        },
        {
          id: 'FLD-GM-013',
          type: 'vital-sign',
          label: 'SpO2',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.spo2',
          order: 3,
        },
        {
          id: 'FLD-GM-014',
          type: 'vital-sign',
          label: 'Weight',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.weight',
          order: 4,
        },
      ],
    },
    {
      id: 'SEC-GM-003',
      title: 'Pertinent Labs',
      order: 2,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-GM-020',
          type: 'lab-value',
          label: 'WBC',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.wbc',
          order: 0,
        },
        {
          id: 'FLD-GM-021',
          type: 'lab-value',
          label: 'Hgb',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.hgb',
          order: 1,
        },
        {
          id: 'FLD-GM-022',
          type: 'lab-value',
          label: 'Na',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.sodium',
          order: 2,
        },
        {
          id: 'FLD-GM-023',
          type: 'lab-value',
          label: 'K',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.potassium',
          order: 3,
        },
        {
          id: 'FLD-GM-024',
          type: 'lab-value',
          label: 'Cr',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.creatinine',
          order: 4,
        },
        {
          id: 'FLD-GM-025',
          type: 'lab-value',
          label: 'Glucose',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.glucose',
          order: 5,
        },
      ],
    },
    {
      id: 'SEC-GM-004',
      title: 'Ins / Outs (24h)',
      order: 3,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-GM-030',
          type: 'number',
          label: 'PO Intake (mL)',
          columnSize: 'medium',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-GM-031',
          type: 'number',
          label: 'IV Fluids (mL)',
          columnSize: 'medium',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-GM-032',
          type: 'number',
          label: 'Urine Output (mL)',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-GM-033',
          type: 'number',
          label: 'Net Balance (mL)',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-GM-005',
      title: 'Assessment & Plan',
      order: 4,
      isCollapsible: false,
      fields: [
        {
          id: 'FLD-GM-040',
          type: 'assessment',
          label: 'Clinical Assessment',
          columnSize: 'large',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-GM-041',
          type: 'plan',
          label: 'Plan',
          columnSize: 'large',
          required: false,
          order: 1,
        },
      ],
    },
    {
      id: 'SEC-GM-006',
      title: 'Tasks / To-Do',
      order: 5,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-GM-050',
          type: 'checkbox',
          label: 'Labs ordered',
          columnSize: 'medium',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-GM-051',
          type: 'checkbox',
          label: 'Imaging ordered',
          columnSize: 'medium',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-GM-052',
          type: 'checkbox',
          label: 'Consult placed',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-GM-053',
          type: 'checkbox',
          label: 'Family updated',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
        {
          id: 'FLD-GM-054',
          type: 'select',
          label: 'Dispo',
          columnSize: 'medium',
          required: false,
          options: ['Continue admit', 'Step-down', 'Discharge today', 'Discharge tomorrow', 'SNF placement', 'Hospice'],
          order: 4,
        },
      ],
    },
  ],
};

// ─── Template 2: ICU ─────────────────────────────────────────────────────────

export const MOCK_TEMPLATE_ICU: RoundingSheetTemplate = {
  id: 'TPL-DEFAULT-002',
  name: 'ICU Daily Assessment',
  description: 'Comprehensive ICU rounding template with organ systems',
  specialty: 'Critical Care',
  isDefault: true,
  isShared: true,
  createdBy: 'USR-002',
  createdByName: 'Dr. James Chen',
  createdAt: '2025-10-15T09:00:00Z',
  updatedAt: '2026-02-01T08:00:00Z',
  useCount: 89,
  lastUsedAt: '2026-02-19T06:00:00Z',
  tags: ['icu', 'critical-care', 'organ-systems'],
  sections: [
    {
      id: 'SEC-ICU-001',
      title: 'Neuro',
      order: 0,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-001',
          type: 'number',
          label: 'GCS',
          columnSize: 'small',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-ICU-002',
          type: 'select',
          label: 'Sedation',
          columnSize: 'medium',
          required: false,
          options: ['None', 'Propofol', 'Precedex', 'Midazolam', 'Fentanyl', 'Ketamine'],
          order: 1,
        },
        {
          id: 'FLD-ICU-003',
          type: 'number',
          label: 'RASS Score',
          columnSize: 'small',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-ICU-004',
          type: 'checkbox',
          label: 'Delirium screen +',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-ICU-002',
      title: 'Cardiovascular',
      order: 1,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-010',
          type: 'vital-sign',
          label: 'BP',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.bp',
          order: 0,
        },
        {
          id: 'FLD-ICU-011',
          type: 'vital-sign',
          label: 'HR',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.hr',
          order: 1,
        },
        {
          id: 'FLD-ICU-012',
          type: 'select',
          label: 'Vasopressor',
          columnSize: 'medium',
          required: false,
          options: ['None', 'Norepinephrine', 'Vasopressin', 'Epinephrine', 'Dopamine', 'Phenylephrine'],
          order: 2,
        },
        {
          id: 'FLD-ICU-013',
          type: 'text',
          label: 'Vasopressor dose',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
        {
          id: 'FLD-ICU-014',
          type: 'checkbox',
          label: 'Troponin trend',
          columnSize: 'medium',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'SEC-ICU-003',
      title: 'Respiratory',
      order: 2,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-020',
          type: 'vital-sign',
          label: 'SpO2',
          columnSize: 'small',
          required: false,
          dataSource: 'vitals.spo2',
          order: 0,
        },
        {
          id: 'FLD-ICU-021',
          type: 'select',
          label: 'O2 delivery',
          columnSize: 'medium',
          required: false,
          options: ['Room air', 'Nasal cannula', 'Face mask', 'NRB', 'HFNC', 'NIV/BiPAP', 'Intubated/Vent'],
          order: 1,
        },
        {
          id: 'FLD-ICU-022',
          type: 'text',
          label: 'Vent mode',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-ICU-023',
          type: 'text',
          label: 'PEEP / FiO2 / TV',
          columnSize: 'large',
          required: false,
          order: 3,
        },
        {
          id: 'FLD-ICU-024',
          type: 'text',
          label: 'ABG / Plateau P',
          columnSize: 'medium',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'SEC-ICU-004',
      title: 'Renal / Fluids',
      order: 3,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-030',
          type: 'lab-value',
          label: 'Cr',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.creatinine',
          order: 0,
        },
        {
          id: 'FLD-ICU-031',
          type: 'lab-value',
          label: 'BUN',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.bun',
          order: 1,
        },
        {
          id: 'FLD-ICU-032',
          type: 'number',
          label: 'UO (mL/hr)',
          columnSize: 'small',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-ICU-033',
          type: 'number',
          label: 'Net balance (mL)',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
        {
          id: 'FLD-ICU-034',
          type: 'checkbox',
          label: 'CRRT running',
          columnSize: 'medium',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'SEC-ICU-005',
      title: 'GI / Nutrition',
      order: 4,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-040',
          type: 'select',
          label: 'Diet / Nutrition',
          columnSize: 'medium',
          required: false,
          options: ['NPO', 'Clear liquids', 'Regular', 'TPN', 'EN - NG tube', 'EN - J tube'],
          order: 0,
        },
        {
          id: 'FLD-ICU-041',
          type: 'checkbox',
          label: 'PPI / stress ulcer ppx',
          columnSize: 'medium',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-ICU-042',
          type: 'checkbox',
          label: 'Bowel regimen',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
      ],
    },
    {
      id: 'SEC-ICU-006',
      title: 'ID / Microbiology',
      order: 5,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-050',
          type: 'lab-value',
          label: 'WBC',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.wbc',
          order: 0,
        },
        {
          id: 'FLD-ICU-051',
          type: 'text',
          label: 'Active cultures',
          columnSize: 'large',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-ICU-052',
          type: 'text',
          label: 'Antibiotics (Day #)',
          columnSize: 'large',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-ICU-053',
          type: 'select',
          label: 'Fever',
          columnSize: 'small',
          required: false,
          options: ['No', 'Yes', 'Defervesced'],
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-ICU-007',
      title: 'Hematology',
      order: 6,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-060',
          type: 'lab-value',
          label: 'Hgb',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.hgb',
          order: 0,
        },
        {
          id: 'FLD-ICU-061',
          type: 'lab-value',
          label: 'INR',
          columnSize: 'small',
          required: false,
          dataSource: 'labs.inr',
          order: 1,
        },
        {
          id: 'FLD-ICU-062',
          type: 'checkbox',
          label: 'DVT ppx active',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-ICU-063',
          type: 'checkbox',
          label: 'Blood products today',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-ICU-008',
      title: 'Lines / Drains / Tubes',
      order: 7,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-070',
          type: 'text',
          label: 'Central line (site / day)',
          columnSize: 'large',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-ICU-071',
          type: 'text',
          label: 'A-line (site)',
          columnSize: 'medium',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-ICU-072',
          type: 'checkbox',
          label: 'Foley present',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-ICU-073',
          type: 'text',
          label: 'Other drains / tubes',
          columnSize: 'large',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-ICU-009',
      title: 'Assessment & Plan',
      order: 8,
      isCollapsible: false,
      fields: [
        {
          id: 'FLD-ICU-080',
          type: 'assessment',
          label: 'Assessment',
          columnSize: 'large',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-ICU-081',
          type: 'plan',
          label: 'Plan',
          columnSize: 'large',
          required: false,
          order: 1,
        },
      ],
    },
    {
      id: 'SEC-ICU-010',
      title: 'Disposition',
      order: 9,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-ICU-090',
          type: 'select',
          label: 'Disposition',
          columnSize: 'medium',
          required: false,
          options: ['Continue ICU', 'Step-down ready', 'Palliative / Comfort care', 'Family meeting needed'],
          order: 0,
        },
        {
          id: 'FLD-ICU-091',
          type: 'note',
          label: 'Family / Goals of care note',
          columnSize: 'large',
          required: false,
          order: 1,
        },
      ],
    },
  ],
};

// ─── Template 3: Surgical ────────────────────────────────────────────────────

export const MOCK_TEMPLATE_SURGICAL: RoundingSheetTemplate = {
  id: 'TPL-DEFAULT-003',
  name: 'Surgical Service Rounding',
  description: 'Post-operative surgical rounding sheet',
  specialty: 'Surgery',
  isDefault: true,
  isShared: true,
  createdBy: 'USR-003',
  createdByName: 'Dr. Maria Garcia',
  createdAt: '2025-09-01T07:30:00Z',
  updatedAt: '2026-01-20T09:00:00Z',
  useCount: 67,
  lastUsedAt: '2026-02-18T08:15:00Z',
  tags: ['surgery', 'post-op', 'surgical'],
  sections: [
    {
      id: 'SEC-SX-001',
      title: 'Procedure / POD',
      order: 0,
      isCollapsible: false,
      fields: [
        {
          id: 'FLD-SX-001',
          type: 'text',
          label: 'Procedure performed',
          columnSize: 'large',
          required: true,
          order: 0,
        },
        {
          id: 'FLD-SX-002',
          type: 'number',
          label: 'Post-op Day #',
          columnSize: 'small',
          required: true,
          order: 1,
        },
        {
          id: 'FLD-SX-003',
          type: 'text',
          label: 'Surgeon',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-SX-004',
          type: 'select',
          label: 'Anesthesia type',
          columnSize: 'medium',
          required: false,
          options: ['General', 'Spinal', 'Epidural', 'Regional', 'MAC', 'Local'],
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-SX-002',
      title: 'Wound',
      order: 1,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-SX-010',
          type: 'select',
          label: 'Wound status',
          columnSize: 'medium',
          required: false,
          options: ['Clean / dry / intact', 'Mild erythema', 'Serosanguineous drainage', 'Purulent drainage', 'Dehiscence'],
          order: 0,
        },
        {
          id: 'FLD-SX-011',
          type: 'select',
          label: 'Dressing',
          columnSize: 'medium',
          required: false,
          options: ['Dry gauze', 'Non-adherent', 'Wet-to-dry', 'VAC/wound vac', 'Steri-strips', 'Open to air'],
          order: 1,
        },
        {
          id: 'FLD-SX-012',
          type: 'checkbox',
          label: 'Staples / sutures intact',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-SX-013',
          type: 'note',
          label: 'Wound notes',
          columnSize: 'large',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-SX-003',
      title: 'Drains & Tubes',
      order: 2,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-SX-020',
          type: 'text',
          label: 'JP drain output (mL)',
          columnSize: 'medium',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-SX-021',
          type: 'text',
          label: 'Drain character',
          columnSize: 'medium',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-SX-022',
          type: 'checkbox',
          label: 'Foley present',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
        {
          id: 'FLD-SX-023',
          type: 'checkbox',
          label: 'NGT present',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
        {
          id: 'FLD-SX-024',
          type: 'text',
          label: 'Other drains',
          columnSize: 'large',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'SEC-SX-004',
      title: 'Diet & Activity',
      order: 3,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-SX-030',
          type: 'select',
          label: 'Diet',
          columnSize: 'medium',
          required: false,
          options: ['NPO', 'Ice chips', 'Clear liquids', 'Full liquids', 'Soft', 'Regular', 'TPN'],
          order: 0,
        },
        {
          id: 'FLD-SX-031',
          type: 'checkbox',
          label: 'Tolerating diet',
          columnSize: 'medium',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-SX-032',
          type: 'select',
          label: 'Activity',
          columnSize: 'medium',
          required: false,
          options: ['Bedrest', 'OOB chair', 'Ambulate w/ assist', 'Ambulate independently', 'Ambulate tid'],
          order: 2,
        },
        {
          id: 'FLD-SX-033',
          type: 'checkbox',
          label: 'PT/OT ordered',
          columnSize: 'medium',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'SEC-SX-005',
      title: 'Pain Management',
      order: 4,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-SX-040',
          type: 'number',
          label: 'Pain score (0-10)',
          columnSize: 'small',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-SX-041',
          type: 'select',
          label: 'Pain regimen',
          columnSize: 'medium',
          required: false,
          options: ['PCA', 'Scheduled opioid', 'PRN opioid', 'Non-opioid only', 'Regional block', 'Epidural'],
          order: 1,
        },
        {
          id: 'FLD-SX-042',
          type: 'checkbox',
          label: 'Pain controlled',
          columnSize: 'medium',
          required: false,
          order: 2,
        },
      ],
    },
    {
      id: 'SEC-SX-006',
      title: 'DVT / VTE Prophylaxis',
      order: 5,
      isCollapsible: true,
      fields: [
        {
          id: 'FLD-SX-050',
          type: 'checkbox',
          label: 'SCDs in place',
          columnSize: 'medium',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-SX-051',
          type: 'select',
          label: 'Chemical ppx',
          columnSize: 'medium',
          required: false,
          options: ['None / contraindicated', 'Heparin SQ', 'Enoxaparin', 'Fondaparinux', 'Aspirin', 'Warfarin'],
          order: 1,
        },
      ],
    },
    {
      id: 'SEC-SX-007',
      title: 'Assessment & Plan',
      order: 6,
      isCollapsible: false,
      fields: [
        {
          id: 'FLD-SX-060',
          type: 'assessment',
          label: 'Assessment',
          columnSize: 'large',
          required: false,
          order: 0,
        },
        {
          id: 'FLD-SX-061',
          type: 'plan',
          label: 'Plan',
          columnSize: 'large',
          required: false,
          order: 1,
        },
        {
          id: 'FLD-SX-062',
          type: 'select',
          label: 'Expected discharge',
          columnSize: 'medium',
          required: false,
          options: ['Today', 'Tomorrow', 'POD 2-3', 'POD 4-5', 'Extended stay', 'SNF'],
          order: 2,
        },
      ],
    },
  ],
};

// ─── All templates array ──────────────────────────────────────────────────────

export const MOCK_ROUNDING_SHEET_TEMPLATES: RoundingSheetTemplate[] = [
  MOCK_TEMPLATE_GENERAL_MED,
  MOCK_TEMPLATE_ICU,
  MOCK_TEMPLATE_SURGICAL,
];

// ─── Mock filled-in rounding sheets ──────────────────────────────────────────

export const MOCK_ROUNDING_SHEET_IN_PROGRESS: RoundingSheet = {
  id: 'SHEET-001',
  templateId: 'TPL-DEFAULT-001',
  templateName: 'General Medicine Rounding',
  date: '2026-02-20',
  shift: 'day',
  unit: '4 South - General Medicine',
  status: 'in-progress',
  createdBy: 'USR-001',
  createdByName: 'Dr. Sarah Wilson',
  createdAt: '2026-02-20T06:30:00Z',
  updatedAt: '2026-02-20T09:15:00Z',
  patients: [
    {
      patientId: 'PAT-001',
      patientName: 'John Smith',
      room: '412A',
      mrn: 'MRN-001234',
      admitDate: '2026-02-17',
      attendingPhysician: 'Dr. Sarah Wilson',
      diagnosis: 'Community-acquired pneumonia',
      entries: [
        { fieldId: 'FLD-GM-001', value: '412A' },
        { fieldId: 'FLD-GM-002', value: 'Community-acquired pneumonia' },
        { fieldId: 'FLD-GM-003', value: '4' },
        { fieldId: 'FLD-GM-004', value: 'Full Code' },
        { fieldId: 'FLD-GM-010', value: '124/78' },
        { fieldId: 'FLD-GM-011', value: '88' },
        { fieldId: 'FLD-GM-012', value: '37.8' },
        { fieldId: 'FLD-GM-013', value: '94%' },
        { fieldId: 'FLD-GM-014', value: '72 kg' },
        { fieldId: 'FLD-GM-020', value: '12.4' },
        { fieldId: 'FLD-GM-021', value: '10.2' },
        { fieldId: 'FLD-GM-022', value: '138' },
        { fieldId: 'FLD-GM-023', value: '4.0' },
        { fieldId: 'FLD-GM-024', value: '0.9' },
        { fieldId: 'FLD-GM-025', value: '108' },
        { fieldId: 'FLD-GM-030', value: '800' },
        { fieldId: 'FLD-GM-031', value: '500' },
        { fieldId: 'FLD-GM-032', value: '1100' },
        { fieldId: 'FLD-GM-033', value: '+200' },
        { fieldId: 'FLD-GM-040', value: 'CAP improving on Ceftriaxone/Azithromycin. Still requiring 2L O2 NC but improving from 4L yesterday.' },
        { fieldId: 'FLD-GM-041', value: '1. Continue IV abx, transition to PO if tolerating\n2. Repeat CXR today\n3. Wean O2 as tolerated\n4. Plan discharge tomorrow if stable' },
        { fieldId: 'FLD-GM-050', value: 'true' },
        { fieldId: 'FLD-GM-051', value: 'true' },
        { fieldId: 'FLD-GM-052', value: 'false' },
        { fieldId: 'FLD-GM-053', value: 'true' },
        { fieldId: 'FLD-GM-054', value: 'Discharge tomorrow' },
      ],
    },
    {
      patientId: 'PAT-002',
      patientName: 'Margaret O\'Brien',
      room: '408B',
      mrn: 'MRN-001289',
      admitDate: '2026-02-19',
      attendingPhysician: 'Dr. Sarah Wilson',
      diagnosis: 'Acute decompensated heart failure',
      entries: [
        { fieldId: 'FLD-GM-001', value: '408B' },
        { fieldId: 'FLD-GM-002', value: 'Acute decompensated heart failure (EF 25%)' },
        { fieldId: 'FLD-GM-003', value: '2' },
        { fieldId: 'FLD-GM-004', value: 'DNR / DNI' },
        { fieldId: 'FLD-GM-010', value: '98/60' },
        { fieldId: 'FLD-GM-011', value: '96' },
        { fieldId: 'FLD-GM-012', value: '37.1' },
        { fieldId: 'FLD-GM-013', value: '96%' },
        { fieldId: 'FLD-GM-014', value: '88 kg' },
        { fieldId: 'FLD-GM-020', value: '9.8' },
        { fieldId: 'FLD-GM-021', value: '8.9' },
        { fieldId: 'FLD-GM-022', value: '136' },
        { fieldId: 'FLD-GM-023', value: '3.6' },
        { fieldId: 'FLD-GM-024', value: '1.4' },
        { fieldId: 'FLD-GM-025', value: '102' },
        { fieldId: 'FLD-GM-030', value: '400' },
        { fieldId: 'FLD-GM-031', value: '0' },
        { fieldId: 'FLD-GM-032', value: '2200' },
        { fieldId: 'FLD-GM-033', value: '-1800' },
        { fieldId: 'FLD-GM-040', value: 'ADHF, net negative 1.8L overnight. BNP trending down 4200 -> 2800. Legs less edematous.' },
        { fieldId: 'FLD-GM-041', value: '1. Continue IV Lasix 80 mg BID\n2. Strict I&Os, goal -1L/day\n3. Cardiology following\n4. Hold discharge pending response' },
        { fieldId: 'FLD-GM-054', value: 'Continue admit' },
      ],
    },
    {
      patientId: 'PAT-003',
      patientName: 'David Kim',
      room: '415C',
      mrn: 'MRN-001301',
      admitDate: '2026-02-20',
      attendingPhysician: 'Dr. Sarah Wilson',
      diagnosis: 'Hypertensive urgency, DM2 uncontrolled',
      entries: [
        { fieldId: 'FLD-GM-001', value: '415C' },
        { fieldId: 'FLD-GM-002', value: 'Hypertensive urgency; DM2 uncontrolled' },
        { fieldId: 'FLD-GM-003', value: '1' },
        { fieldId: 'FLD-GM-004', value: 'Full Code' },
        { fieldId: 'FLD-GM-010', value: '178/104' },
        { fieldId: 'FLD-GM-011', value: '92' },
        { fieldId: 'FLD-GM-012', value: '37.2' },
        { fieldId: 'FLD-GM-013', value: '98%' },
        { fieldId: 'FLD-GM-014', value: '95 kg' },
        { fieldId: 'FLD-GM-025', value: '342' },
        { fieldId: 'FLD-GM-040', value: 'Admitted overnight with BP 200/120. Slowly improving with IV labetalol. Glucose poorly controlled, endocrine consulted.' },
        { fieldId: 'FLD-GM-041', value: '1. IV labetalol, titrate to SBP < 160\n2. Insulin drip per endocrine recs\n3. Repeat BMP in 4h\n4. Neuro exam - ruling out hypertensive emergency' },
        { fieldId: 'FLD-GM-052', value: 'true' },
        { fieldId: 'FLD-GM-054', value: 'Continue admit' },
      ],
    },
  ],
};

export const MOCK_ROUNDING_SHEET_COMPLETED: RoundingSheet = {
  id: 'SHEET-002',
  templateId: 'TPL-DEFAULT-002',
  templateName: 'ICU Daily Assessment',
  date: '2026-02-19',
  shift: 'day',
  unit: 'Medical ICU - 6 North',
  status: 'completed',
  createdBy: 'USR-002',
  createdByName: 'Dr. James Chen',
  createdAt: '2026-02-19T06:00:00Z',
  updatedAt: '2026-02-19T18:45:00Z',
  patients: [
    {
      patientId: 'PAT-011',
      patientName: 'Robert Hernandez',
      room: 'MICU-1',
      mrn: 'MRN-001455',
      admitDate: '2026-02-15',
      attendingPhysician: 'Dr. James Chen',
      diagnosis: 'Septic shock (abdominal source)',
      entries: [
        { fieldId: 'FLD-ICU-001', value: '12' },
        { fieldId: 'FLD-ICU-002', value: 'Propofol' },
        { fieldId: 'FLD-ICU-003', value: '-1' },
        { fieldId: 'FLD-ICU-010', value: '102/64' },
        { fieldId: 'FLD-ICU-011', value: '105' },
        { fieldId: 'FLD-ICU-012', value: 'Norepinephrine' },
        { fieldId: 'FLD-ICU-013', value: '0.08 mcg/kg/min (weaning)' },
        { fieldId: 'FLD-ICU-020', value: '97%' },
        { fieldId: 'FLD-ICU-021', value: 'Intubated/Vent' },
        { fieldId: 'FLD-ICU-022', value: 'AC/VC' },
        { fieldId: 'FLD-ICU-023', value: 'PEEP 8 / FiO2 40% / TV 420' },
        { fieldId: 'FLD-ICU-030', value: '2.1' },
        { fieldId: 'FLD-ICU-031', value: '28' },
        { fieldId: 'FLD-ICU-032', value: '45' },
        { fieldId: 'FLD-ICU-050', value: '18.2' },
        { fieldId: 'FLD-ICU-051', value: 'BCx x2 (pending day 2), UCx, peritoneal cx' },
        { fieldId: 'FLD-ICU-052', value: 'Pip/tazo (Day 5), Fluconazole (Day 3)' },
        { fieldId: 'FLD-ICU-060', value: '8.4' },
        { fieldId: 'FLD-ICU-061', value: '1.8' },
        { fieldId: 'FLD-ICU-080', value: 'Septic shock improving. Vasopressor weaning. Source control achieved (ex-lap POD 4). Ventilator weaning tomorrow.' },
        { fieldId: 'FLD-ICU-081', value: '1. Continue norepi wean\n2. SAT/SBT tomorrow\n3. Follow culture results\n4. Surgery rounding jointly' },
        { fieldId: 'FLD-ICU-090', value: 'Continue ICU' },
      ],
    },
    {
      patientId: 'PAT-012',
      patientName: 'Linda Patel',
      room: 'MICU-3',
      mrn: 'MRN-001462',
      admitDate: '2026-02-18',
      attendingPhysician: 'Dr. James Chen',
      diagnosis: 'ARDS secondary to COVID-19',
      entries: [
        { fieldId: 'FLD-ICU-001', value: '8' },
        { fieldId: 'FLD-ICU-002', value: 'Propofol' },
        { fieldId: 'FLD-ICU-003', value: '-2' },
        { fieldId: 'FLD-ICU-004', value: 'true' },
        { fieldId: 'FLD-ICU-010', value: '118/72' },
        { fieldId: 'FLD-ICU-011', value: '112' },
        { fieldId: 'FLD-ICU-020', value: '91%' },
        { fieldId: 'FLD-ICU-021', value: 'Intubated/Vent' },
        { fieldId: 'FLD-ICU-022', value: 'APRV' },
        { fieldId: 'FLD-ICU-023', value: 'PEEP 14 / FiO2 70% / Phigh 28' },
        { fieldId: 'FLD-ICU-080', value: 'ARDS P/F ratio 88. Severe ARDS requiring APRV. Prone positioning yesterday improved oxygenation transiently.' },
        { fieldId: 'FLD-ICU-081', value: '1. Prone again today x 16h\n2. Consider ECMO consult if P/F < 80\n3. Continue empiric remdesivir\n4. Family meeting today re: prognosis' },
        { fieldId: 'FLD-ICU-090', value: 'Continue ICU' },
        { fieldId: 'FLD-ICU-091', value: 'Family meeting scheduled 3pm with Dr. Chen and palliative care. Daughter (HCP) present.' },
      ],
    },
    {
      patientId: 'PAT-013',
      patientName: 'William Torres',
      room: 'MICU-5',
      mrn: 'MRN-001478',
      admitDate: '2026-02-16',
      attendingPhysician: 'Dr. James Chen',
      diagnosis: 'DKA, Type 1 DM',
      entries: [
        { fieldId: 'FLD-ICU-001', value: '15' },
        { fieldId: 'FLD-ICU-002', value: 'None' },
        { fieldId: 'FLD-ICU-003', value: '0' },
        { fieldId: 'FLD-ICU-010', value: '132/80' },
        { fieldId: 'FLD-ICU-011', value: '88' },
        { fieldId: 'FLD-ICU-020', value: '99%' },
        { fieldId: 'FLD-ICU-021', value: 'Nasal cannula' },
        { fieldId: 'FLD-ICU-030', value: '1.0' },
        { fieldId: 'FLD-ICU-032', value: '80' },
        { fieldId: 'FLD-ICU-033', value: '-500' },
        { fieldId: 'FLD-ICU-050', value: '8.9' },
        { fieldId: 'FLD-ICU-060', value: '11.2' },
        { fieldId: 'FLD-ICU-080', value: 'DKA resolving. pH 7.34 (was 7.1 on admit). Anion gap closing. Insulin drip rate decreased.' },
        { fieldId: 'FLD-ICU-081', value: '1. Transition to subcutaneous insulin when AG closes\n2. Endocrine following\n3. Target step-down tomorrow\n4. Diabetes education consult' },
        { fieldId: 'FLD-ICU-090', value: 'Step-down ready' },
      ],
    },
    {
      patientId: 'PAT-014',
      patientName: 'Susan Nakamura',
      room: 'MICU-7',
      mrn: 'MRN-001490',
      admitDate: '2026-02-14',
      attendingPhysician: 'Dr. James Chen',
      diagnosis: 'Acute respiratory failure, COPD exacerbation',
      entries: [
        { fieldId: 'FLD-ICU-001', value: '14' },
        { fieldId: 'FLD-ICU-002', value: 'None' },
        { fieldId: 'FLD-ICU-003', value: '0' },
        { fieldId: 'FLD-ICU-010', value: '144/88' },
        { fieldId: 'FLD-ICU-011', value: '78' },
        { fieldId: 'FLD-ICU-020', value: '95%' },
        { fieldId: 'FLD-ICU-021', value: 'NIV/BiPAP' },
        { fieldId: 'FLD-ICU-022', value: 'BiPAP 12/6, FiO2 40%' },
        { fieldId: 'FLD-ICU-050', value: '10.2' },
        { fieldId: 'FLD-ICU-052', value: 'Azithromycin (Day 7), Ceftriaxone (Day 7 - last day)' },
        { fieldId: 'FLD-ICU-060', value: '11.8' },
        { fieldId: 'FLD-ICU-080', value: 'COPD exacerbation improving. BiPAP use down to 8h/day from 24h. Tolerating trials of high-flow NC.' },
        { fieldId: 'FLD-ICU-081', value: '1. Continue steroid taper\n2. Last day of antibiotics\n3. Pulm rehab evaluation\n4. Step-down plan if tolerates HFNC trial tonight' },
        { fieldId: 'FLD-ICU-090', value: 'Step-down ready' },
      ],
    },
  ],
};

export const MOCK_ROUNDING_SHEETS: RoundingSheet[] = [
  MOCK_ROUNDING_SHEET_IN_PROGRESS,
  MOCK_ROUNDING_SHEET_COMPLETED,
];
