import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { TimelineEvent } from '../models/timeline.model';

const USE_MOCK = true;
const MOCK_DELAY = 300;

function daysAgo(d: number): string {
  const date = new Date();
  date.setDate(date.getDate() - d);
  return date.toISOString();
}

function hoursAgo(h: number): string {
  const date = new Date();
  date.setHours(date.getHours() - h);
  return date.toISOString();
}

@Injectable({ providedIn: 'root' })
export class TimelineService {
  getPatientTimeline(patientId: string): Observable<TimelineEvent[]> {
    if (USE_MOCK) {
      return of(this.generateMockTimeline(patientId)).pipe(delay(MOCK_DELAY));
    }
    return of([]);
  }

  private generateMockTimeline(patientId: string): TimelineEvent[] {
    return [
      // --- TODAY ---
      {
        id: 'TL-001',
        patientId,
        domain: 'encounter',
        timestamp: hoursAgo(2),
        title: 'Office Visit - Follow-up',
        description:
          'Follow-up for diabetes management and hypertension. HbA1c reviewed. Medication adjustments discussed.',
        icon: 'pi pi-calendar',
        color: '#3b82f6',
        sourceId: 'ENC-2026-001',
        sourceType: 'encounter',
        provider: 'Dr. Sarah Chen',
        location: 'Springfield Family Medicine',
        status: 'in-progress',
        problemCodes: ['E11.9', 'I10'],
        problemNames: ['Type 2 Diabetes', 'Hypertension'],
        tags: ['follow-up', 'chronic-care'],
      },

      // --- 1 DAY AGO ---
      {
        id: 'TL-002',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(1),
        title: 'HbA1c: 7.2%',
        description:
          'Hemoglobin A1c slightly above target (goal <7.0%). Improved from prior value of 7.8% — trending in right direction.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-001',
        sourceType: 'lab',
        provider: 'Quest Diagnostics',
        status: 'final',
        labValue: '7.2',
        labUnit: '%',
        labTrend: 'decreasing',
        isAbnormal: true,
        isCritical: false,
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['diabetes-monitoring'],
      },
      {
        id: 'TL-003',
        patientId,
        domain: 'vital',
        timestamp: daysAgo(1),
        title: 'Vitals Recorded: BP 138/88',
        description:
          'Blood pressure 138/88 mmHg (elevated), Heart Rate 76 bpm, Temperature 98.4°F, Weight 187 lbs, SpO2 98%.',
        icon: 'pi pi-heart',
        color: '#ef4444',
        sourceId: 'VIT-2026-001',
        sourceType: 'vital',
        provider: 'RN Amanda Torres',
        location: 'Springfield Family Medicine',
        status: 'recorded',
        labValue: '138/88',
        labUnit: 'mmHg',
        labTrend: 'stable',
        isAbnormal: true,
        problemCodes: ['I10'],
        problemNames: ['Hypertension'],
        tags: ['vitals'],
      },

      // --- 5 DAYS AGO ---
      {
        id: 'TL-004',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(5),
        title: 'Comprehensive Metabolic Panel',
        description:
          'BMP results: Glucose 142 mg/dL (H), BUN 18, Creatinine 1.1, eGFR 68, Sodium 139, Potassium 4.1. Mild hyperglycemia noted.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-002',
        sourceType: 'lab',
        provider: 'LabCorp',
        status: 'final',
        labValue: '142',
        labUnit: 'mg/dL',
        labTrend: 'stable',
        isAbnormal: true,
        isCritical: false,
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['metabolic-panel'],
      },
      {
        id: 'TL-005',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(5),
        title: 'Lipid Panel',
        description:
          'Total Cholesterol 198 mg/dL, LDL 118 mg/dL (borderline high), HDL 48 mg/dL, Triglycerides 162 mg/dL.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-003',
        sourceType: 'lab',
        provider: 'LabCorp',
        status: 'final',
        labValue: '118',
        labUnit: 'mg/dL (LDL)',
        labTrend: 'decreasing',
        isAbnormal: false,
        problemCodes: ['E78.5'],
        problemNames: ['Hyperlipidemia'],
        tags: ['lipid-panel', 'cardiovascular'],
      },

      // --- 8 DAYS AGO ---
      {
        id: 'TL-006',
        patientId,
        domain: 'prescription',
        timestamp: daysAgo(8),
        title: 'Metformin 1000mg — Dose Increased',
        description:
          'Metformin increased from 500mg to 1000mg twice daily. Patient counseled on GI side effects and importance of adherence.',
        icon: 'pi pi-list',
        color: '#10b981',
        sourceId: 'RX-2026-001',
        sourceType: 'prescription',
        provider: 'Dr. Sarah Chen',
        status: 'active',
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['medication-change', 'diabetes'],
      },

      // --- 14 DAYS AGO ---
      {
        id: 'TL-007',
        patientId,
        domain: 'note',
        timestamp: daysAgo(14),
        title: 'Progress Note — Diabetes & HTN Review',
        description:
          'Patient reports improved diet compliance. Exercise 3x/week. Denies chest pain, dyspnea, or hypoglycemic episodes. Continue current plan with medication adjustment.',
        icon: 'pi pi-file-edit',
        color: '#f59e0b',
        sourceId: 'NOTE-2026-001',
        sourceType: 'note',
        provider: 'Dr. Sarah Chen',
        status: 'signed',
        problemCodes: ['E11.9', 'I10'],
        problemNames: ['Type 2 Diabetes', 'Hypertension'],
        tags: ['progress-note', 'signed'],
      },

      // --- 21 DAYS AGO ---
      {
        id: 'TL-008',
        patientId,
        domain: 'imaging',
        timestamp: daysAgo(21),
        title: 'Chest X-Ray — PA and Lateral',
        description:
          'No acute cardiopulmonary process. Mild cardiomegaly. No pleural effusion or pneumothorax. Lung fields clear.',
        icon: 'pi pi-image',
        color: '#ec4899',
        sourceId: 'IMG-2026-001',
        sourceType: 'imaging',
        provider: 'Dr. Michael Ortiz, Radiology',
        location: 'Springfield Regional Hospital',
        status: 'final',
        isAbnormal: true,
        problemCodes: ['I10', 'I51.7'],
        problemNames: ['Hypertension', 'Cardiomegaly'],
        tags: ['radiology', 'chest'],
      },
      {
        id: 'TL-009',
        patientId,
        domain: 'vital',
        timestamp: daysAgo(21),
        title: 'Vitals Recorded: BP 145/92',
        description:
          'Blood pressure 145/92 mmHg (Stage 2 HTN), Heart Rate 82 bpm, Temperature 98.6°F, Weight 188 lbs.',
        icon: 'pi pi-heart',
        color: '#ef4444',
        sourceId: 'VIT-2026-002',
        sourceType: 'vital',
        provider: 'RN James Owens',
        location: 'Springfield Regional Hospital',
        status: 'recorded',
        labValue: '145/92',
        labUnit: 'mmHg',
        labTrend: 'increasing',
        isAbnormal: true,
        isCritical: false,
        problemCodes: ['I10'],
        problemNames: ['Hypertension'],
        tags: ['vitals'],
      },

      // --- 30 DAYS AGO ---
      {
        id: 'TL-010',
        patientId,
        domain: 'encounter',
        timestamp: daysAgo(30),
        title: 'Emergency Department Visit',
        description:
          'Patient presented with headache and BP 168/104. Received IV labetalol. Admitted for observation. Discharged after 6 hours with medication adjustments.',
        icon: 'pi pi-calendar',
        color: '#3b82f6',
        sourceId: 'ENC-2026-002',
        sourceType: 'encounter',
        provider: 'Dr. Kevin Walsh, Emergency Medicine',
        location: 'Springfield Regional Hospital — ED',
        status: 'completed',
        isAbnormal: true,
        isCritical: true,
        problemCodes: ['I10', 'R51.9'],
        problemNames: ['Hypertension Crisis', 'Headache'],
        tags: ['emergency', 'acute'],
      },
      {
        id: 'TL-011',
        patientId,
        domain: 'prescription',
        timestamp: daysAgo(30),
        title: 'Amlodipine 10mg — Started',
        description:
          'Calcium channel blocker added to antihypertensive regimen following ED visit for hypertensive urgency.',
        icon: 'pi pi-list',
        color: '#10b981',
        sourceId: 'RX-2026-002',
        sourceType: 'prescription',
        provider: 'Dr. Kevin Walsh',
        status: 'active',
        problemCodes: ['I10'],
        problemNames: ['Hypertension'],
        tags: ['new-medication', 'hypertension'],
      },

      // --- 45 DAYS AGO ---
      {
        id: 'TL-012',
        patientId,
        domain: 'referral',
        timestamp: daysAgo(45),
        title: 'Referral to Endocrinology',
        description:
          'Referred to Dr. Linda Park (Endocrinology) for diabetes management optimization. HbA1c persistently above 7.5% despite medication adjustments.',
        icon: 'pi pi-directions',
        color: '#64748b',
        sourceId: 'REF-2026-001',
        sourceType: 'referral',
        provider: 'Dr. Sarah Chen',
        status: 'pending',
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['referral', 'specialist'],
      },
      {
        id: 'TL-013',
        patientId,
        domain: 'note',
        timestamp: daysAgo(45),
        title: 'Telephone Encounter — Medication Concern',
        description:
          'Patient called reporting dizziness after starting lisinopril. Advised to hold morning dose and recheck BP at home. Will follow up in 2 days.',
        icon: 'pi pi-file-edit',
        color: '#f59e0b',
        sourceId: 'NOTE-2026-002',
        sourceType: 'note',
        provider: 'Dr. Sarah Chen',
        status: 'signed',
        problemCodes: ['I10'],
        problemNames: ['Hypertension'],
        tags: ['telephone', 'medication-concern'],
      },

      // --- 60 DAYS AGO ---
      {
        id: 'TL-014',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(60),
        title: 'HbA1c: 7.8%',
        description:
          'Hemoglobin A1c remains above target. No improvement from previous value of 7.9%. Medication adherence counseling provided.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-004',
        sourceType: 'lab',
        provider: 'Quest Diagnostics',
        status: 'final',
        labValue: '7.8',
        labUnit: '%',
        labTrend: 'stable',
        isAbnormal: true,
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['diabetes-monitoring'],
      },
      {
        id: 'TL-015',
        patientId,
        domain: 'encounter',
        timestamp: daysAgo(60),
        title: 'Telehealth Visit — Chronic Care',
        description:
          'Video visit for chronic condition management. Patient reports fatigue. Reviewed recent labs. Ordered repeat HbA1c and CMP in 60 days.',
        icon: 'pi pi-calendar',
        color: '#3b82f6',
        sourceId: 'ENC-2026-003',
        sourceType: 'encounter',
        provider: 'Dr. Sarah Chen',
        location: 'Telehealth',
        status: 'completed',
        problemCodes: ['E11.9', 'I10'],
        problemNames: ['Type 2 Diabetes', 'Hypertension'],
        tags: ['telehealth', 'chronic-care'],
      },

      // --- 75 DAYS AGO ---
      {
        id: 'TL-016',
        patientId,
        domain: 'procedure',
        timestamp: daysAgo(75),
        title: 'Diabetic Foot Exam',
        description:
          'Annual diabetic foot exam performed. Monofilament sensation intact bilaterally. No ulcers, calluses, or deformities noted. Referred to podiatry for preventive care.',
        icon: 'pi pi-wrench',
        color: '#06b6d4',
        sourceId: 'PROC-2026-001',
        sourceType: 'procedure',
        provider: 'Dr. Sarah Chen',
        location: 'Springfield Family Medicine',
        status: 'completed',
        problemCodes: ['E11.40'],
        problemNames: ['Diabetic Neuropathy'],
        tags: ['annual-exam', 'preventive'],
      },
      {
        id: 'TL-017',
        patientId,
        domain: 'vital',
        timestamp: daysAgo(75),
        title: 'Vitals Recorded: BP 132/84',
        description:
          'Blood pressure 132/84 mmHg (Stage 1 HTN), Heart Rate 74 bpm, Temperature 98.2°F, Weight 191 lbs.',
        icon: 'pi pi-heart',
        color: '#ef4444',
        sourceId: 'VIT-2026-003',
        sourceType: 'vital',
        provider: 'RN Amanda Torres',
        location: 'Springfield Family Medicine',
        status: 'recorded',
        labValue: '132/84',
        labUnit: 'mmHg',
        labTrend: 'decreasing',
        isAbnormal: true,
        problemCodes: ['I10'],
        problemNames: ['Hypertension'],
        tags: ['vitals'],
      },

      // --- 90 DAYS AGO ---
      {
        id: 'TL-018',
        patientId,
        domain: 'prescription',
        timestamp: daysAgo(90),
        title: 'Lisinopril 10mg — Started',
        description:
          'ACE inhibitor initiated for combined benefit in hypertension and diabetic nephropathy prevention. Patient counseled on dry cough as possible side effect.',
        icon: 'pi pi-list',
        color: '#10b981',
        sourceId: 'RX-2026-003',
        sourceType: 'prescription',
        provider: 'Dr. Sarah Chen',
        status: 'active',
        problemCodes: ['I10', 'E11.65'],
        problemNames: ['Hypertension', 'Diabetic CKD'],
        tags: ['new-medication', 'ace-inhibitor'],
      },
      {
        id: 'TL-019',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(90),
        title: 'Urinalysis with Micro',
        description:
          'Urine microalbumin 42 mg/g creatinine (elevated). Early sign of diabetic nephropathy. Renal function panel ordered.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-005',
        sourceType: 'lab',
        provider: 'Quest Diagnostics',
        status: 'final',
        labValue: '42',
        labUnit: 'mg/g Cr',
        labTrend: 'increasing',
        isAbnormal: true,
        isCritical: false,
        problemCodes: ['E11.65'],
        problemNames: ['Diabetic CKD'],
        tags: ['nephrology', 'diabetes-complication'],
      },

      // --- 105 DAYS AGO ---
      {
        id: 'TL-020',
        patientId,
        domain: 'external',
        timestamp: daysAgo(105),
        title: 'External Record: Cardiologist Consult',
        description:
          'Consult note from Dr. Raymond Gupta (Cardiology, Metro Heart Center). EKG: normal sinus rhythm. Echo: EF 55%, mild LVH. Continue current management.',
        icon: 'pi pi-globe',
        color: '#d946ef',
        sourceId: 'EXT-2026-001',
        sourceType: 'external',
        provider: 'Dr. Raymond Gupta, Cardiology',
        location: 'Metro Heart Center',
        status: 'reviewed',
        problemCodes: ['I10', 'I51.7'],
        problemNames: ['Hypertension', 'LVH'],
        tags: ['external', 'cardiology', 'consult'],
      },

      // --- 120 DAYS AGO ---
      {
        id: 'TL-021',
        patientId,
        domain: 'encounter',
        timestamp: daysAgo(120),
        title: 'Office Visit — Annual Physical',
        description:
          'Annual preventive exam. Height 5\'10", Weight 193 lbs, BMI 27.7. Vaccines reviewed — flu shot administered. Referral to cardiology for LVH on prior echo.',
        icon: 'pi pi-calendar',
        color: '#3b82f6',
        sourceId: 'ENC-2026-004',
        sourceType: 'encounter',
        provider: 'Dr. Sarah Chen',
        location: 'Springfield Family Medicine',
        status: 'completed',
        problemCodes: ['Z00.00'],
        problemNames: ['Annual Wellness Exam'],
        tags: ['annual-physical', 'preventive'],
      },
      {
        id: 'TL-022',
        patientId,
        domain: 'imaging',
        timestamp: daysAgo(120),
        title: 'Echocardiogram',
        description:
          'Transthoracic echocardiogram. Ejection fraction 55% (preserved). Mild concentric LVH consistent with hypertension. No valvular abnormalities.',
        icon: 'pi pi-image',
        color: '#ec4899',
        sourceId: 'IMG-2026-002',
        sourceType: 'imaging',
        provider: 'Dr. Raymond Gupta, Cardiology',
        location: 'Metro Heart Center',
        status: 'final',
        isAbnormal: true,
        problemCodes: ['I10', 'I51.7'],
        problemNames: ['Hypertension', 'LVH'],
        tags: ['echo', 'cardiology'],
      },
      {
        id: 'TL-023',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(120),
        title: 'CBC with Differential',
        description:
          'Complete blood count within normal limits. WBC 6.8, Hgb 13.9, Hct 42.1%, Platelets 224. No anemia or leukocytosis.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-006',
        sourceType: 'lab',
        provider: 'Quest Diagnostics',
        status: 'final',
        labValue: '13.9',
        labUnit: 'g/dL',
        labTrend: 'stable',
        isAbnormal: false,
        tags: ['cbc', 'annual'],
      },

      // --- 150 DAYS AGO ---
      {
        id: 'TL-024',
        patientId,
        domain: 'note',
        timestamp: daysAgo(150),
        title: 'Nurse Triage Note — Sick Visit',
        description:
          'Patient called with reports of increased thirst, polyuria, and fatigue x 3 days. Advised urgent appointment. Glucose fingerstick 288 mg/dL in office.',
        icon: 'pi pi-file-edit',
        color: '#f59e0b',
        sourceId: 'NOTE-2026-003',
        sourceType: 'note',
        provider: 'RN Amanda Torres',
        status: 'signed',
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['triage', 'urgent'],
      },
      {
        id: 'TL-025',
        patientId,
        domain: 'prescription',
        timestamp: daysAgo(150),
        title: 'Metformin 500mg — Started',
        description:
          'Metformin initiated for newly diagnosed Type 2 Diabetes. Low dose to minimize GI side effects. Patient provided with diabetes education materials.',
        icon: 'pi pi-list',
        color: '#10b981',
        sourceId: 'RX-2026-004',
        sourceType: 'prescription',
        provider: 'Dr. Sarah Chen',
        status: 'active',
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['new-medication', 'diabetes', 'new-diagnosis'],
      },

      // --- 165 DAYS AGO ---
      {
        id: 'TL-026',
        patientId,
        domain: 'lab',
        timestamp: daysAgo(165),
        title: 'HbA1c: 9.1% — Initial Diagnosis',
        description:
          'Hemoglobin A1c markedly elevated at 9.1%. Consistent with new diagnosis of Type 2 Diabetes Mellitus. Diabetes education and lifestyle counseling ordered.',
        icon: 'pi pi-chart-bar',
        color: '#8b5cf6',
        sourceId: 'LAB-2026-007',
        sourceType: 'lab',
        provider: 'Quest Diagnostics',
        status: 'final',
        labValue: '9.1',
        labUnit: '%',
        labTrend: 'increasing',
        isAbnormal: true,
        isCritical: true,
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['new-diagnosis', 'diabetes-monitoring'],
      },

      // --- 180 DAYS AGO ---
      {
        id: 'TL-027',
        patientId,
        domain: 'procedure',
        timestamp: daysAgo(180),
        title: 'Retinal Eye Exam',
        description:
          'Dilated fundus exam by ophthalmology. No evidence of diabetic retinopathy at this time. Recommended annual follow-up.',
        icon: 'pi pi-wrench',
        color: '#06b6d4',
        sourceId: 'PROC-2026-002',
        sourceType: 'procedure',
        provider: 'Dr. Priya Nair, Ophthalmology',
        location: 'Clear Vision Eye Care',
        status: 'completed',
        problemCodes: ['E11.9', 'Z01.00'],
        problemNames: ['Type 2 Diabetes', 'Eye Exam'],
        tags: ['ophthalmology', 'preventive', 'diabetes-screening'],
      },
      {
        id: 'TL-028',
        patientId,
        domain: 'referral',
        timestamp: daysAgo(180),
        title: 'Referral to Diabetes Education',
        description:
          'Referred to certified diabetes educator (CDE) program for DSMES (Diabetes Self-Management Education and Support). 3-session program.',
        icon: 'pi pi-directions',
        color: '#64748b',
        sourceId: 'REF-2026-002',
        sourceType: 'referral',
        provider: 'Dr. Sarah Chen',
        status: 'completed',
        problemCodes: ['E11.9'],
        problemNames: ['Type 2 Diabetes'],
        tags: ['education', 'diabetes', 'self-management'],
      },
      {
        id: 'TL-029',
        patientId,
        domain: 'vital',
        timestamp: daysAgo(180),
        title: 'Vitals Recorded: BP 128/82',
        description:
          'Blood pressure 128/82 mmHg, Heart Rate 78 bpm, Temperature 98.6°F, Weight 196 lbs. BMI 28.1.',
        icon: 'pi pi-heart',
        color: '#ef4444',
        sourceId: 'VIT-2026-004',
        sourceType: 'vital',
        provider: 'RN James Owens',
        location: 'Springfield Family Medicine',
        status: 'recorded',
        labValue: '128/82',
        labUnit: 'mmHg',
        labTrend: 'stable',
        isAbnormal: false,
        tags: ['vitals'],
      },
    ];
  }
}
