import {
  ImagingOrder,
  ImagingProcedure,
  ImagingFacility,
  ImagingReport,
  ImagingStudy,
  ImagingModality,
  BodyRegion
} from '../../models/imaging.model';

// ============ Mock Procedures ============

export const MOCK_IMAGING_PROCEDURES: ImagingProcedure[] = [
  // X-Ray procedures
  {
    procedureCode: 'XR-CHEST-2V',
    procedureName: 'Chest X-Ray, 2 Views',
    name: 'Chest X-Ray, 2 Views',
    modality: 'xray',
    bodyRegion: 'chest',
    cptCode: '71046',
    description: 'PA and lateral chest radiograph',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 15,
    technicalFee: 85,
    professionalFee: 35,
    isCommon: true
  },
  {
    procedureCode: 'XR-KNEE-3V',
    procedureName: 'Knee X-Ray, 3 Views',
    name: 'Knee X-Ray, 3 Views',
    modality: 'xray',
    bodyRegion: 'lower-extremity',
    cptCode: '73562',
    description: 'AP, lateral, and oblique knee radiographs',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 15,
    technicalFee: 75,
    professionalFee: 30,
    isCommon: true
  },
  {
    procedureCode: 'XR-SPINE-L-4V',
    procedureName: 'Lumbar Spine X-Ray, 4 Views',
    name: 'Lumbar Spine X-Ray, 4 Views',
    modality: 'xray',
    bodyRegion: 'spine',
    cptCode: '72110',
    description: 'AP, lateral, and oblique lumbar spine radiographs',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 20,
    technicalFee: 95,
    professionalFee: 40,
    isCommon: true
  },

  // CT procedures
  {
    procedureCode: 'CT-HEAD-WO',
    procedureName: 'CT Head without Contrast',
    name: 'CT Head without Contrast',
    modality: 'ct',
    bodyRegion: 'head',
    cptCode: '70450',
    description: 'Non-contrast CT of the brain',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 15,
    technicalFee: 350,
    professionalFee: 95,
    isCommon: true
  },
  {
    procedureCode: 'CT-HEAD-W',
    procedureName: 'CT Head with Contrast',
    name: 'CT Head with Contrast',
    modality: 'ct',
    bodyRegion: 'head',
    cptCode: '70460',
    description: 'CT of the brain with IV contrast',
    contrastOptions: ['iv'],
    defaultContrast: 'iv',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 30,
    technicalFee: 450,
    professionalFee: 115,
    isCommon: true
  },
  {
    procedureCode: 'CT-CHEST-W',
    procedureName: 'CT Chest with Contrast',
    name: 'CT Chest with Contrast',
    modality: 'ct',
    bodyRegion: 'chest',
    cptCode: '71260',
    description: 'CT of the chest with IV contrast',
    contrastOptions: ['none', 'iv'],
    defaultContrast: 'iv',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 20,
    technicalFee: 400,
    professionalFee: 105,
    isCommon: true
  },
  {
    procedureCode: 'CT-ABD-PEL-W',
    procedureName: 'CT Abdomen/Pelvis with Contrast',
    name: 'CT Abdomen/Pelvis with Contrast',
    modality: 'ct',
    bodyRegion: 'abdomen',
    cptCode: '74177',
    description: 'CT of abdomen and pelvis with IV contrast',
    contrastOptions: ['oral', 'iv', 'oral-iv'],
    defaultContrast: 'oral-iv',
    requiresPrep: true,
    prepRequired: true,
    prepInstructions: 'NPO 4 hours. Drink oral contrast 1-2 hours before exam.',
    estimatedDuration: 30,
    technicalFee: 550,
    professionalFee: 135,
    isCommon: true
  },
  {
    procedureCode: 'CTA-CHEST-PE',
    procedureName: 'CT Angiography Chest (PE Protocol)',
    name: 'CT Angiography Chest (PE Protocol)',
    modality: 'ct',
    bodyRegion: 'chest',
    cptCode: '71275',
    description: 'CT angiography of chest for pulmonary embolism',
    contrastOptions: ['iv'],
    defaultContrast: 'iv',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 20,
    technicalFee: 600,
    professionalFee: 150,
    isCommon: true
  },

  // MRI procedures
  {
    procedureCode: 'MRI-BRAIN-WO',
    procedureName: 'MRI Brain without Contrast',
    name: 'MRI Brain without Contrast',
    modality: 'mri',
    bodyRegion: 'head',
    cptCode: '70551',
    description: 'MRI of the brain without contrast',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 45,
    technicalFee: 800,
    professionalFee: 180,
    isCommon: true
  },
  {
    procedureCode: 'MRI-BRAIN-WWO',
    procedureName: 'MRI Brain with and without Contrast',
    name: 'MRI Brain with and without Contrast',
    modality: 'mri',
    bodyRegion: 'head',
    cptCode: '70553',
    description: 'MRI of the brain with and without contrast',
    contrastOptions: ['iv'],
    defaultContrast: 'iv',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 60,
    technicalFee: 1000,
    professionalFee: 220,
    isCommon: true
  },
  {
    procedureCode: 'MRI-SPINE-L-WO',
    procedureName: 'MRI Lumbar Spine without Contrast',
    name: 'MRI Lumbar Spine without Contrast',
    modality: 'mri',
    bodyRegion: 'spine',
    cptCode: '72148',
    description: 'MRI of lumbar spine without contrast',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 45,
    technicalFee: 750,
    professionalFee: 170,
    isCommon: true
  },
  {
    procedureCode: 'MRI-KNEE-WO',
    procedureName: 'MRI Knee without Contrast',
    name: 'MRI Knee without Contrast',
    modality: 'mri',
    bodyRegion: 'lower-extremity',
    cptCode: '73721',
    description: 'MRI of the knee without contrast',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 45,
    technicalFee: 700,
    professionalFee: 160,
    isCommon: true
  },

  // Ultrasound procedures
  {
    procedureCode: 'US-ABD-COMP',
    procedureName: 'Ultrasound Abdomen Complete',
    name: 'Ultrasound Abdomen Complete',
    modality: 'ultrasound',
    bodyRegion: 'abdomen',
    cptCode: '76700',
    description: 'Complete abdominal ultrasound',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: true,
    prepRequired: true,
    prepInstructions: 'NPO 8 hours before exam',
    estimatedDuration: 30,
    technicalFee: 250,
    professionalFee: 75,
    isCommon: true
  },
  {
    procedureCode: 'US-THYROID',
    procedureName: 'Ultrasound Thyroid',
    name: 'Ultrasound Thyroid',
    modality: 'ultrasound',
    bodyRegion: 'neck',
    cptCode: '76536',
    description: 'Thyroid ultrasound with soft tissue of neck',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 20,
    technicalFee: 180,
    professionalFee: 55,
    isCommon: true
  },

  // Mammography procedures
  {
    procedureCode: 'MAMMO-SCREEN-BILAT',
    procedureName: 'Screening Mammography, Bilateral',
    name: 'Screening Mammography, Bilateral',
    modality: 'mammography',
    bodyRegion: 'chest',
    cptCode: '77067',
    description: 'Bilateral screening mammography',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 20,
    technicalFee: 150,
    professionalFee: 50,
    isCommon: true
  },
  {
    procedureCode: 'MAMMO-DIAG-BILAT',
    procedureName: 'Diagnostic Mammography, Bilateral',
    name: 'Diagnostic Mammography, Bilateral',
    modality: 'mammography',
    bodyRegion: 'chest',
    cptCode: '77066',
    description: 'Bilateral diagnostic mammography',
    contrastOptions: ['none'],
    defaultContrast: 'none',
    requiresPrep: false,
    prepRequired: false,
    estimatedDuration: 30,
    technicalFee: 200,
    professionalFee: 65,
    isCommon: true
  }
];

// ============ Mock Facilities ============

export const MOCK_IMAGING_FACILITIES: ImagingFacility[] = [
  {
    facilityId: 'FAC-001',
    id: 'FAC-001',
    name: 'Springfield Medical Center - Radiology',
    facilityType: 'hospital',
    address: '123 Medical Center Dr, Springfield, IL 62701',
    phone: '(217) 555-0100',
    fax: '(217) 555-0101',
    modalities: ['xray', 'ct', 'mri', 'ultrasound', 'mammography', 'fluoroscopy', 'nuclear'],
    is24Hour: true,
    acceptsWalkIns: true,
    pacsIntegrated: true,
    hasPacsIntegration: true,
    supportsEOrders: true,
    isPreferred: true
  },
  {
    facilityId: 'FAC-002',
    id: 'FAC-002',
    name: 'Advanced Imaging Center',
    facilityType: 'imaging-center',
    address: '456 Diagnostic Blvd, Suite 200, Springfield, IL 62702',
    phone: '(217) 555-0200',
    fax: '(217) 555-0201',
    modalities: ['ct', 'mri', 'ultrasound', 'mammography', 'dexa'],
    is24Hour: false,
    acceptsWalkIns: false,
    pacsIntegrated: true,
    hasPacsIntegration: true,
    supportsEOrders: true,
    isPreferred: false
  },
  {
    facilityId: 'FAC-003',
    id: 'FAC-003',
    name: 'Community Urgent Care - X-Ray',
    facilityType: 'clinic',
    address: '789 Wellness Way, Springfield, IL 62703',
    phone: '(217) 555-0300',
    fax: '(217) 555-0301',
    modalities: ['xray', 'ultrasound'],
    is24Hour: false,
    acceptsWalkIns: true,
    pacsIntegrated: false,
    hasPacsIntegration: false,
    supportsEOrders: false,
    isPreferred: false
  },
  {
    facilityId: 'FAC-004',
    id: 'FAC-004',
    name: 'Regional PET/CT Center',
    facilityType: 'imaging-center',
    address: '321 Oncology Center, Springfield, IL 62704',
    phone: '(217) 555-0400',
    fax: '(217) 555-0401',
    modalities: ['pet', 'ct', 'nuclear'],
    is24Hour: false,
    acceptsWalkIns: false,
    pacsIntegrated: true,
    hasPacsIntegration: true,
    supportsEOrders: true,
    isPreferred: false
  }
];

// ============ Helper Functions ============

function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

function hoursAgo(hours: number): string {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date.toISOString();
}

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
}

function daysAgoDate(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString().split('T')[0];
}

// ============ Mock Orders ============

export const MOCK_IMAGING_ORDERS: ImagingOrder[] = [
  // --- Order 1: Chest X-Ray - Fresh (ordered 1 month ago, expires in ~11 months) ---
  {
    orderId: 'IMG-2026-001',
    accessionNumber: 'ACC-2026-0001',
    patientId: 'P001',
    patientName: 'John Smith',
    patientDOB: '1965-03-15',
    modality: 'xray',
    procedure: MOCK_IMAGING_PROCEDURES.find(p => p.procedureCode === 'XR-CHEST-2V')!,
    procedureCode: 'XR-CHEST-2V',
    procedureName: 'Chest X-Ray, 2 Views',
    bodyRegion: 'chest',
    status: 'final',
    priority: 'routine',
    category: 'diagnostic',
    contrastRequired: false,
    contrastType: 'none',
    orderingProviderId: 'PROV-001',
    orderingProviderName: 'Dr. Sarah Chen',
    performingFacilityId: 'FAC-001',
    performingFacilityName: 'Springfield Medical Center - Radiology',
    diagnosisCodes: [{ code: 'J18.9', description: 'Pneumonia, unspecified' }],
    clinicalHistory: 'Cough and fever, rule out pneumonia',
    reasonForExam: 'Cough, fever, shortness of breath',
    orderedDate: daysAgo(30),
    scheduledDate: daysAgo(29),
    performedDate: daysAgo(29),
    reportedDate: daysAgo(28),
    expirationDate: daysFromNow(335),
    pregnancyStatus: 'not-applicable',
    report: {
      reportId: 'RPT-2026-001',
      orderId: 'IMG-2026-001',
      status: 'final',
      indication: 'Cough and fever',
      findings: 'No acute cardiopulmonary process. Lungs are clear. Heart size is normal.',
      impression: 'Normal chest radiograph.',
      hasCriticalFindings: false,
      radiologistId: 'RAD-001',
      radiologistName: 'Dr. Patricia Kim',
      signedAt: daysAgo(28),
      createdAt: daysAgo(28),
      updatedAt: daysAgo(28),
    },
    createdAt: daysAgo(30),
    createdBy: 'PROV-001',
    updatedAt: daysAgo(28),
    updatedBy: 'RAD-001',
  },

  // --- Order 2: MRI Brain - Expiring soon (ordered 11 months ago, expires in ~6 weeks) ---
  {
    orderId: 'IMG-2025-002',
    accessionNumber: 'ACC-2025-0042',
    patientId: 'P002',
    patientName: 'Sarah Johnson',
    patientDOB: '1978-07-22',
    modality: 'mri',
    procedure: MOCK_IMAGING_PROCEDURES.find(p => p.procedureCode === 'MRI-BRAIN-WO')!,
    procedureCode: 'MRI-BRAIN-WO',
    procedureName: 'MRI Brain without Contrast',
    bodyRegion: 'head',
    status: 'final',
    priority: 'routine',
    category: 'diagnostic',
    contrastRequired: false,
    contrastType: 'none',
    orderingProviderId: 'PROV-001',
    orderingProviderName: 'Dr. Sarah Chen',
    performingFacilityId: 'FAC-002',
    performingFacilityName: 'Advanced Imaging Center',
    diagnosisCodes: [{ code: 'G43.909', description: 'Migraine, unspecified' }],
    clinicalHistory: 'Recurrent migraines, evaluate for structural abnormality',
    orderedDate: daysAgo(334),
    scheduledDate: daysAgo(325),
    performedDate: daysAgo(325),
    reportedDate: daysAgo(323),
    expirationDate: daysFromNow(31),
    pregnancyStatus: 'not-pregnant',
    claustrophobia: false,
    report: {
      reportId: 'RPT-2025-042',
      orderId: 'IMG-2025-002',
      status: 'final',
      indication: 'Recurrent migraines',
      findings: 'No intracranial mass, hemorrhage, or acute infarct. White matter appears normal for age.',
      impression: 'Normal brain MRI without contrast.',
      hasCriticalFindings: false,
      radiologistId: 'RAD-002',
      radiologistName: 'Dr. Marcus Webb',
      signedAt: daysAgo(323),
      createdAt: daysAgo(323),
      updatedAt: daysAgo(323),
    },
    createdAt: daysAgo(334),
    createdBy: 'PROV-001',
    updatedAt: daysAgo(323),
    updatedBy: 'RAD-002',
  },

  // --- Order 3: CT Abdomen - Expired (ordered 14 months ago, expired 2 months ago) ---
  {
    orderId: 'IMG-2024-003',
    accessionNumber: 'ACC-2024-0187',
    patientId: 'P003',
    patientName: 'Michael Brown',
    patientDOB: '1955-11-08',
    modality: 'ct',
    procedure: MOCK_IMAGING_PROCEDURES.find(p => p.procedureCode === 'CT-ABD-PEL-W')!,
    procedureCode: 'CT-ABD-PEL-W',
    procedureName: 'CT Abdomen/Pelvis with Contrast',
    bodyRegion: 'abdomen',
    status: 'final',
    priority: 'urgent',
    category: 'diagnostic',
    contrastRequired: true,
    contrastType: 'oral-iv',
    orderingProviderId: 'PROV-002',
    orderingProviderName: 'Dr. James Rivera',
    performingFacilityId: 'FAC-001',
    performingFacilityName: 'Springfield Medical Center - Radiology',
    diagnosisCodes: [{ code: 'R10.9', description: 'Unspecified abdominal pain' }],
    clinicalHistory: 'Abdominal pain, elevated liver enzymes',
    orderedDate: daysAgo(425),
    scheduledDate: daysAgo(422),
    performedDate: daysAgo(422),
    reportedDate: daysAgo(420),
    expirationDate: daysAgoDate(60),
    pregnancyStatus: 'not-applicable',
    renalFunction: { creatinine: 0.9, gfr: 85 },
    report: {
      reportId: 'RPT-2024-187',
      orderId: 'IMG-2024-003',
      status: 'final',
      indication: 'Abdominal pain, elevated liver enzymes',
      findings: 'Liver is normal in size with homogeneous attenuation. No biliary ductal dilatation. No free fluid.',
      impression: 'No acute abdominal pathology identified.',
      hasCriticalFindings: false,
      radiologistId: 'RAD-001',
      radiologistName: 'Dr. Patricia Kim',
      signedAt: daysAgo(420),
      createdAt: daysAgo(420),
      updatedAt: daysAgo(420),
    },
    createdAt: daysAgo(425),
    createdBy: 'PROV-002',
    updatedAt: daysAgo(420),
    updatedBy: 'RAD-001',
  },

  // --- Order 4: Mammography - Valid with 24-month default (ordered 18 months ago, expires in ~6 months) ---
  {
    orderId: 'IMG-2024-004',
    accessionNumber: 'ACC-2024-0088',
    patientId: 'P006',
    patientName: 'Jennifer Martinez',
    patientDOB: '1985-04-18',
    modality: 'mammography',
    procedure: MOCK_IMAGING_PROCEDURES.find(p => p.procedureCode === 'MAMMO-SCREEN-BILAT')!,
    procedureCode: 'MAMMO-SCREEN-BILAT',
    procedureName: 'Screening Mammography, Bilateral',
    bodyRegion: 'chest',
    status: 'final',
    priority: 'routine',
    category: 'screening',
    contrastRequired: false,
    contrastType: 'none',
    orderingProviderId: 'PROV-001',
    orderingProviderName: 'Dr. Sarah Chen',
    performingFacilityId: 'FAC-002',
    performingFacilityName: 'Advanced Imaging Center',
    diagnosisCodes: [{ code: 'Z12.31', description: 'Encounter for screening mammogram for malignant neoplasm of breast' }],
    clinicalHistory: 'Annual screening mammogram',
    orderedDate: daysAgo(547),
    scheduledDate: daysAgo(540),
    performedDate: daysAgo(540),
    reportedDate: daysAgo(538),
    expirationDate: daysFromNow(188),
    pregnancyStatus: 'not-pregnant',
    report: {
      reportId: 'RPT-2024-088',
      orderId: 'IMG-2024-004',
      status: 'final',
      indication: 'Annual screening mammogram',
      findings: 'Bilateral mammography performed. Breast composition is heterogeneously dense. No suspicious mass or calcifications.',
      impression: 'No mammographic evidence of malignancy. BI-RADS category 1: Negative.',
      hasCriticalFindings: false,
      radiologistId: 'RAD-002',
      radiologistName: 'Dr. Marcus Webb',
      signedAt: daysAgo(538),
      createdAt: daysAgo(538),
      updatedAt: daysAgo(538),
    },
    createdAt: daysAgo(547),
    createdBy: 'PROV-001',
    updatedAt: daysAgo(538),
    updatedBy: 'RAD-002',
  },

  // --- Order 5: Lumbar Spine X-Ray - Pending/Scheduled (no expiration yet) ---
  {
    orderId: 'IMG-2026-005',
    patientId: 'P005',
    patientName: 'Robert Wilson',
    patientDOB: '1948-09-12',
    modality: 'xray',
    procedure: MOCK_IMAGING_PROCEDURES.find(p => p.procedureCode === 'XR-SPINE-L-4V')!,
    procedureCode: 'XR-SPINE-L-4V',
    procedureName: 'Lumbar Spine X-Ray, 4 Views',
    bodyRegion: 'spine',
    status: 'scheduled',
    priority: 'routine',
    category: 'diagnostic',
    contrastRequired: false,
    contrastType: 'none',
    orderingProviderId: 'PROV-002',
    orderingProviderName: 'Dr. James Rivera',
    performingFacilityId: 'FAC-003',
    performingFacilityName: 'Community Urgent Care - X-Ray',
    diagnosisCodes: [{ code: 'M54.5', description: 'Low back pain' }],
    clinicalHistory: 'Chronic low back pain, evaluate for degenerative changes',
    orderedDate: daysAgo(2),
    scheduledDate: daysFromNow(3),
    pregnancyStatus: 'not-applicable',
    createdAt: daysAgo(2),
    createdBy: 'PROV-002',
    updatedAt: daysAgo(2),
    updatedBy: 'PROV-002',
  },
];

// Export counts for dashboard
export const IMAGING_STATS = {
  total: MOCK_IMAGING_ORDERS.length,
  pending: MOCK_IMAGING_ORDERS.filter(o => o.status === 'pending').length,
  scheduled: MOCK_IMAGING_ORDERS.filter(o => o.status === 'scheduled').length,
  inProgress: MOCK_IMAGING_ORDERS.filter(o => o.status === 'in-progress').length,
  preliminary: MOCK_IMAGING_ORDERS.filter(o => o.status === 'preliminary').length,
  final: MOCK_IMAGING_ORDERS.filter(o => o.status === 'final').length,
  critical: MOCK_IMAGING_ORDERS.filter(o => o.report?.hasCriticalFindings).length
};
