import { LabOrder, LabTest, LabPanel, LabFacility, LabResult } from '../../models/lab.model';

// Mock Lab Tests
export const MOCK_LAB_TESTS: LabTest[] = [
  // Chemistry
  { id: 'test-001', testCode: 'GLU', code: 'GLU', testName: 'Glucose', name: 'Glucose', loincCode: '2345-7', cptCode: '82947', category: 'chemistry', specimenType: 'blood', fastingRequired: true, fastingHours: 8, turnaroundTime: '24 hours', price: 15 },
  { id: 'test-002', testCode: 'BUN', code: 'BUN', testName: 'Blood Urea Nitrogen', name: 'Blood Urea Nitrogen', loincCode: '3094-0', cptCode: '84520', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  { id: 'test-003', testCode: 'CREAT', code: 'CREAT', testName: 'Creatinine', name: 'Creatinine', loincCode: '2160-0', cptCode: '82565', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  { id: 'test-004', testCode: 'NA', code: 'NA', testName: 'Sodium', name: 'Sodium', loincCode: '2951-2', cptCode: '84295', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 10 },
  { id: 'test-005', testCode: 'K', code: 'K', testName: 'Potassium', name: 'Potassium', loincCode: '2823-3', cptCode: '84132', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 10 },
  { id: 'test-006', testCode: 'CL', code: 'CL', testName: 'Chloride', name: 'Chloride', loincCode: '2075-0', cptCode: '82435', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 10 },
  { id: 'test-007', testCode: 'CO2', code: 'CO2', testName: 'Carbon Dioxide', name: 'Carbon Dioxide', loincCode: '2028-9', cptCode: '82374', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 10 },
  { id: 'test-008', testCode: 'CA', code: 'CA', testName: 'Calcium', name: 'Calcium', loincCode: '17861-6', cptCode: '82310', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  
  // Hematology
  { id: 'test-010', testCode: 'WBC', code: 'WBC', testName: 'White Blood Cell Count', name: 'White Blood Cell Count', loincCode: '6690-2', cptCode: '85048', category: 'hematology', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 8 },
  { id: 'test-011', testCode: 'RBC', code: 'RBC', testName: 'Red Blood Cell Count', name: 'Red Blood Cell Count', loincCode: '789-8', cptCode: '85041', category: 'hematology', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 8 },
  { id: 'test-012', testCode: 'HGB', code: 'HGB', testName: 'Hemoglobin', name: 'Hemoglobin', loincCode: '718-7', cptCode: '85018', category: 'hematology', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 8 },
  { id: 'test-013', testCode: 'HCT', code: 'HCT', testName: 'Hematocrit', name: 'Hematocrit', loincCode: '4544-3', cptCode: '85014', category: 'hematology', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 8 },
  { id: 'test-014', testCode: 'PLT', code: 'PLT', testName: 'Platelet Count', name: 'Platelet Count', loincCode: '777-3', cptCode: '85049', category: 'hematology', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 8 },

  // Lipids
  { id: 'test-020', testCode: 'CHOL', code: 'CHOL', testName: 'Total Cholesterol', name: 'Total Cholesterol', loincCode: '2093-3', cptCode: '82465', category: 'lipid', specimenType: 'blood', fastingRequired: true, fastingHours: 12, turnaroundTime: '24 hours', price: 15 },
  { id: 'test-021', testCode: 'TRIG', code: 'TRIG', testName: 'Triglycerides', name: 'Triglycerides', loincCode: '2571-8', cptCode: '84478', category: 'lipid', specimenType: 'blood', fastingRequired: true, fastingHours: 12, turnaroundTime: '24 hours', price: 15 },
  { id: 'test-022', testCode: 'HDL', code: 'HDL', testName: 'HDL Cholesterol', name: 'HDL Cholesterol', loincCode: '2085-9', cptCode: '83718', category: 'lipid', specimenType: 'blood', fastingRequired: true, fastingHours: 12, turnaroundTime: '24 hours', price: 18 },
  { id: 'test-023', testCode: 'LDL', code: 'LDL', testName: 'LDL Cholesterol', name: 'LDL Cholesterol', loincCode: '13457-7', cptCode: '83721', category: 'lipid', specimenType: 'blood', fastingRequired: true, fastingHours: 12, turnaroundTime: '24 hours', price: 18 },

  // Thyroid
  { id: 'test-030', testCode: 'TSH', code: 'TSH', testName: 'Thyroid Stimulating Hormone', name: 'Thyroid Stimulating Hormone', loincCode: '3016-3', cptCode: '84443', category: 'thyroid', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 35 },
  { id: 'test-031', testCode: 'FT4', code: 'FT4', testName: 'Free T4', name: 'Free T4', loincCode: '3024-7', cptCode: '84439', category: 'thyroid', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 35 },
  { id: 'test-032', testCode: 'FT3', code: 'FT3', testName: 'Free T3', name: 'Free T3', loincCode: '3051-0', cptCode: '84481', category: 'thyroid', specimenType: 'blood', fastingRequired: false, turnaroundTime: '48 hours', price: 40 },

  // Liver
  { id: 'test-040', testCode: 'ALT', code: 'ALT', testName: 'Alanine Aminotransferase', name: 'Alanine Aminotransferase', loincCode: '1742-6', cptCode: '84460', category: 'liver', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  { id: 'test-041', testCode: 'AST', code: 'AST', testName: 'Aspartate Aminotransferase', name: 'Aspartate Aminotransferase', loincCode: '1920-8', cptCode: '84450', category: 'liver', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  { id: 'test-042', testCode: 'ALP', code: 'ALP', testName: 'Alkaline Phosphatase', name: 'Alkaline Phosphatase', loincCode: '6768-6', cptCode: '84075', category: 'liver', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  { id: 'test-043', testCode: 'TBIL', code: 'TBIL', testName: 'Total Bilirubin', name: 'Total Bilirubin', loincCode: '1975-2', cptCode: '82247', category: 'liver', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 12 },
  { id: 'test-044', testCode: 'ALB', code: 'ALB', testName: 'Albumin', name: 'Albumin', loincCode: '1751-7', cptCode: '82040', category: 'liver', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 10 },

  // Diabetes
  { id: 'test-050', testCode: 'HBA1C', code: 'HBA1C', testName: 'Hemoglobin A1c', name: 'Hemoglobin A1c', loincCode: '4548-4', cptCode: '83036', category: 'chemistry', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 25 },

  // Cardiac
  { id: 'test-060', testCode: 'TROP', code: 'TROP', testName: 'Troponin I', name: 'Troponin I', loincCode: '10839-9', cptCode: '84484', category: 'cardiac', specimenType: 'blood', fastingRequired: false, turnaroundTime: '1 hour', price: 45 },
  { id: 'test-061', testCode: 'BNP', code: 'BNP', testName: 'B-Natriuretic Peptide', name: 'B-Natriuretic Peptide', loincCode: '30934-4', cptCode: '83880', category: 'cardiac', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 85 },

  // Coagulation
  { id: 'test-070', testCode: 'PT', code: 'PT', testName: 'Prothrombin Time', name: 'Prothrombin Time', loincCode: '5902-2', cptCode: '85610', category: 'coagulation', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 15 },
  { id: 'test-071', testCode: 'INR', code: 'INR', testName: 'International Normalized Ratio', name: 'International Normalized Ratio', loincCode: '6301-6', cptCode: '85610', category: 'coagulation', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 0 },
  { id: 'test-072', testCode: 'PTT', code: 'PTT', testName: 'Partial Thromboplastin Time', name: 'Partial Thromboplastin Time', loincCode: '3173-2', cptCode: '85730', category: 'coagulation', specimenType: 'blood', fastingRequired: false, turnaroundTime: '24 hours', price: 18 },

  // Urinalysis
  { id: 'test-080', testCode: 'UA', code: 'UA', testName: 'Urinalysis with Microscopy', name: 'Urinalysis with Microscopy', loincCode: '24356-8', cptCode: '81001', category: 'urinalysis', specimenType: 'urine', fastingRequired: false, turnaroundTime: '24 hours', price: 20 },
];

// Mock Lab Panels
export const MOCK_LAB_PANELS: LabPanel[] = [
  {
    id: 'panel-001',
    panelCode: 'BMP',
    code: 'BMP',
    panelName: 'Basic Metabolic Panel',
    name: 'Basic Metabolic Panel',
    description: 'Measures glucose, calcium, and electrolytes to assess kidney function and blood sugar',
    category: 'chemistry',
    tests: MOCK_LAB_TESTS.filter(t => ['GLU', 'BUN', 'CREAT', 'NA', 'K', 'CL', 'CO2', 'CA'].includes(t.code)),
    loincCode: '51990-0',
    cptCode: '80048',
    price: 45,
    fastingRequired: true,
    fastingHours: 8,
    specimenType: 'blood',
    turnaroundTime: '24 hours',
    isCommon: true,
  },
  {
    id: 'panel-002',
    panelCode: 'CBC',
    code: 'CBC',
    panelName: 'Complete Blood Count',
    name: 'Complete Blood Count',
    description: 'Evaluates overall health and detects a wide range of disorders including anemia and infection',
    category: 'hematology',
    tests: MOCK_LAB_TESTS.filter(t => ['WBC', 'RBC', 'HGB', 'HCT', 'PLT'].includes(t.code)),
    loincCode: '57021-8',
    cptCode: '85025',
    price: 35,
    fastingRequired: false,
    specimenType: 'blood',
    turnaroundTime: '24 hours',
    isCommon: true,
  },
  {
    id: 'panel-003',
    panelCode: 'LIPID',
    code: 'LIPID',
    panelName: 'Lipid Panel',
    name: 'Lipid Panel',
    description: 'Measures cholesterol and triglycerides to assess cardiovascular disease risk',
    category: 'lipid',
    tests: MOCK_LAB_TESTS.filter(t => ['CHOL', 'TRIG', 'HDL', 'LDL'].includes(t.code)),
    loincCode: '57698-3',
    cptCode: '80061',
    price: 55,
    fastingRequired: true,
    fastingHours: 12,
    specimenType: 'blood',
    turnaroundTime: '24 hours',
    isCommon: true,
  },
  {
    id: 'panel-004',
    panelCode: 'LFT',
    code: 'LFT',
    panelName: 'Liver Function Panel',
    name: 'Liver Function Panel',
    description: 'Assesses liver health and function',
    category: 'liver',
    tests: MOCK_LAB_TESTS.filter(t => ['ALT', 'AST', 'ALP', 'TBIL', 'ALB'].includes(t.code)),
    loincCode: '24325-3',
    cptCode: '80076',
    price: 50,
    fastingRequired: false,
    specimenType: 'blood',
    turnaroundTime: '24 hours',
    isCommon: true,
  },
  {
    id: 'panel-005',
    panelCode: 'THYROID',
    code: 'THYROID',
    panelName: 'Thyroid Panel',
    name: 'Thyroid Panel',
    description: 'Evaluates thyroid gland function',
    category: 'thyroid',
    tests: MOCK_LAB_TESTS.filter(t => ['TSH', 'FT4', 'FT3'].includes(t.code)),
    loincCode: '55789-5',
    cptCode: '84443',
    price: 95,
    fastingRequired: false,
    specimenType: 'blood',
    turnaroundTime: '48 hours',
    isCommon: true,
  },
];

// Mock Lab Facilities
export const MOCK_LAB_FACILITIES: LabFacility[] = [
  {
    id: 'lab-001',
    facilityId: 'lab-001',
    name: 'Quest Diagnostics - Main',
    type: 'reference',
    address: { street: '100 Lab Way', city: 'Springfield', state: 'IL', zipCode: '62701' },
    phone: '(217) 555-0100',
    fax: '(217) 555-0101',
    email: 'orders@questdiag.example.com',
    npi: '1234567890',
    clia: '14D1234567',
    acceptsEOrders: true,
    supportsEOrders: true,
    supportsHL7: true,
    isPreferred: true,
  },
  {
    id: 'lab-002',
    facilityId: 'lab-002',
    name: 'LabCorp Service Center',
    type: 'reference',
    address: { street: '200 Medical Blvd', city: 'Springfield', state: 'IL', zipCode: '62702' },
    phone: '(217) 555-0200',
    fax: '(217) 555-0201',
    email: 'orders@labcorp.example.com',
    npi: '0987654321',
    clia: '14D7654321',
    acceptsEOrders: true,
    supportsEOrders: true,
    supportsHL7: true,
    isPreferred: false,
  },
  {
    id: 'lab-003',
    facilityId: 'lab-003',
    name: 'Springfield General Hospital Lab',
    type: 'hospital',
    address: { street: '500 Hospital Dr', city: 'Springfield', state: 'IL', zipCode: '62703' },
    phone: '(217) 555-0500',
    fax: '(217) 555-0501',
    npi: '1122334455',
    clia: '14D1122334',
    acceptsEOrders: true,
    supportsEOrders: true,
    supportsHL7: true,
    isPreferred: false,
  },
  {
    id: 'lab-004',
    facilityId: 'lab-004',
    name: 'In-House Laboratory',
    type: 'internal',
    address: { street: '123 Clinic Way', city: 'Springfield', state: 'IL', zipCode: '62701' },
    phone: '(217) 555-0123',
    npi: '5566778899',
    clia: '14D5566778',
    acceptsEOrders: false,
    supportsEOrders: false,
    supportsHL7: false,
    isPreferred: true,
  },
];

// Helper to generate dates
const today = new Date();
const daysAgo = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

// Mock Lab Orders with Results
export const MOCK_LAB_ORDERS: LabOrder[] = [
  {
    id: 'order-001',
    orderId: 'ORD-2024-001',
    patientId: 'pat-001',
    patientName: 'John Smith',
    patientMRN: 'MRN-10001',
    patientDOB: '1985-03-15',
    encounterId: 'enc-001',
    orderType: 'lab',
    status: 'final',
    priority: 'routine',
    tests: MOCK_LAB_TESTS.filter(t => ['GLU', 'BUN', 'CREAT', 'NA', 'K', 'CL', 'CO2', 'CA'].includes(t.code)),
    panelCode: 'BMP',
    panelName: 'Basic Metabolic Panel',
    orderingProviderId: 'provider-1',
    orderingProviderName: 'Dr. Sarah Chen',
    orderingProviderNPI: '1234567890',
    performingLabId: 'lab-001',
    performingLabName: 'Quest Diagnostics - Main',
    diagnosisCodes: ['E11.9', 'I10'],
    clinicalNotes: 'Annual diabetes and hypertension monitoring',
    fastingRequired: true,
    fastingHours: 8,
    specimenType: 'blood',
    orderedDate: daysAgo(7),
    scheduledDate: daysAgo(5),
    collectionDate: daysAgo(5),
    receivedDate: daysAgo(5),
    reportedDate: daysAgo(4),
    results: [
      { id: 'res-001', orderId: 'order-001', testId: 'test-001', testCode: 'GLU', testName: 'Glucose', value: '142', valueType: 'numeric', unit: 'mg/dL', referenceRange: '70-99', referenceLow: 70, referenceHigh: 99, interpretation: 'high', isAbnormal: true, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-002', orderId: 'order-001', testId: 'test-002', testCode: 'BUN', testName: 'Blood Urea Nitrogen', value: '18', valueType: 'numeric', unit: 'mg/dL', referenceRange: '7-20', referenceLow: 7, referenceHigh: 20, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-003', orderId: 'order-001', testId: 'test-003', testCode: 'CREAT', testName: 'Creatinine', value: '1.1', valueType: 'numeric', unit: 'mg/dL', referenceRange: '0.7-1.3', referenceLow: 0.7, referenceHigh: 1.3, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-004', orderId: 'order-001', testId: 'test-004', testCode: 'NA', testName: 'Sodium', value: '140', valueType: 'numeric', unit: 'mEq/L', referenceRange: '136-145', referenceLow: 136, referenceHigh: 145, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-005', orderId: 'order-001', testId: 'test-005', testCode: 'K', testName: 'Potassium', value: '4.2', valueType: 'numeric', unit: 'mEq/L', referenceRange: '3.5-5.0', referenceLow: 3.5, referenceHigh: 5.0, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-006', orderId: 'order-001', testId: 'test-006', testCode: 'CL', testName: 'Chloride', value: '101', valueType: 'numeric', unit: 'mEq/L', referenceRange: '98-106', referenceLow: 98, referenceHigh: 106, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-007', orderId: 'order-001', testId: 'test-007', testCode: 'CO2', testName: 'Carbon Dioxide', value: '24', valueType: 'numeric', unit: 'mEq/L', referenceRange: '22-29', referenceLow: 22, referenceHigh: 29, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-008', orderId: 'order-001', testId: 'test-008', testCode: 'CA', testName: 'Calcium', value: '9.5', valueType: 'numeric', unit: 'mg/dL', referenceRange: '8.5-10.5', referenceLow: 8.5, referenceHigh: 10.5, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
    ],
    resultsSummary: 'abnormal',
    createdAt: daysAgo(7),
    createdBy: 'provider-1',
    updatedAt: daysAgo(4),
    updatedBy: 'system',
  },
  {
    id: 'order-002',
    orderId: 'ORD-2024-002',
    patientId: 'pat-001',
    patientName: 'John Smith',
    patientMRN: 'MRN-10001',
    patientDOB: '1985-03-15',
    orderType: 'lab',
    status: 'final',
    priority: 'routine',
    tests: MOCK_LAB_TESTS.filter(t => ['CHOL', 'TRIG', 'HDL', 'LDL'].includes(t.code)),
    panelCode: 'LIPID',
    panelName: 'Lipid Panel',
    orderingProviderId: 'provider-1',
    orderingProviderName: 'Dr. Sarah Chen',
    performingLabId: 'lab-001',
    performingLabName: 'Quest Diagnostics - Main',
    diagnosisCodes: ['E78.5'],
    clinicalNotes: 'Hyperlipidemia monitoring',
    fastingRequired: true,
    fastingHours: 12,
    specimenType: 'blood',
    orderedDate: daysAgo(7),
    collectionDate: daysAgo(5),
    reportedDate: daysAgo(4),
    results: [
      { id: 'res-020', orderId: 'order-002', testId: 'test-020', testCode: 'CHOL', testName: 'Total Cholesterol', value: '225', valueType: 'numeric', unit: 'mg/dL', referenceRange: '<200', referenceHigh: 200, interpretation: 'high', isAbnormal: true, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-021', orderId: 'order-002', testId: 'test-021', testCode: 'TRIG', testName: 'Triglycerides', value: '180', valueType: 'numeric', unit: 'mg/dL', referenceRange: '<150', referenceHigh: 150, interpretation: 'high', isAbnormal: true, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-022', orderId: 'order-002', testId: 'test-022', testCode: 'HDL', testName: 'HDL Cholesterol', value: '42', valueType: 'numeric', unit: 'mg/dL', referenceRange: '>40', referenceLow: 40, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
      { id: 'res-023', orderId: 'order-002', testId: 'test-023', testCode: 'LDL', testName: 'LDL Cholesterol', value: '147', valueType: 'numeric', unit: 'mg/dL', referenceRange: '<100', referenceHigh: 100, interpretation: 'high', isAbnormal: true, isCritical: false, status: 'final', reportedAt: daysAgo(4) },
    ],
    resultsSummary: 'abnormal',
    createdAt: daysAgo(7),
    createdBy: 'provider-1',
    updatedAt: daysAgo(4),
    updatedBy: 'system',
  },
  {
    id: 'order-003',
    orderId: 'ORD-2024-003',
    patientId: 'pat-002',
    patientName: 'Sarah Johnson',
    patientMRN: 'MRN-10002',
    patientDOB: '1990-07-22',
    encounterId: 'enc-002',
    orderType: 'lab',
    status: 'final',
    priority: 'routine',
    tests: [MOCK_LAB_TESTS.find(t => t.code === 'TSH')!],
    orderingProviderId: 'provider-1',
    orderingProviderName: 'Dr. Sarah Chen',
    performingLabId: 'lab-001',
    performingLabName: 'Quest Diagnostics - Main',
    diagnosisCodes: ['E03.9'],
    clinicalNotes: 'Hypothyroidism monitoring, on levothyroxine',
    fastingRequired: false,
    specimenType: 'blood',
    orderedDate: daysAgo(14),
    collectionDate: daysAgo(12),
    reportedDate: daysAgo(11),
    results: [
      { id: 'res-030', orderId: 'order-003', testId: 'test-030', testCode: 'TSH', testName: 'Thyroid Stimulating Hormone', value: '2.5', valueType: 'numeric', unit: 'mIU/L', referenceRange: '0.4-4.0', referenceLow: 0.4, referenceHigh: 4.0, interpretation: 'normal', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(11) },
    ],
    resultsSummary: 'normal',
    createdAt: daysAgo(14),
    createdBy: 'provider-1',
    updatedAt: daysAgo(11),
    updatedBy: 'system',
  },
  {
    id: 'order-004',
    orderId: 'ORD-2024-004',
    patientId: 'pat-003',
    patientName: 'Michael Brown',
    patientMRN: 'MRN-10003',
    patientDOB: '1978-11-08',
    orderType: 'lab',
    status: 'collected',
    priority: 'urgent',
    tests: MOCK_LAB_TESTS.filter(t => ['WBC', 'RBC', 'HGB', 'HCT', 'PLT'].includes(t.code)),
    panelCode: 'CBC',
    panelName: 'Complete Blood Count',
    orderingProviderId: 'provider-2',
    orderingProviderName: 'Dr. Michael Rodriguez',
    performingLabId: 'lab-003',
    performingLabName: 'Springfield General Hospital Lab',
    diagnosisCodes: ['D64.9'],
    clinicalNotes: 'Evaluate for anemia, patient reports fatigue',
    fastingRequired: false,
    specimenType: 'blood',
    orderedDate: daysAgo(1),
    collectionDate: daysAgo(0),
    results: [],
    resultsSummary: 'pending',
    createdAt: daysAgo(1),
    createdBy: 'provider-2',
    updatedAt: daysAgo(0),
    updatedBy: 'system',
  },
  {
    id: 'order-005',
    orderId: 'ORD-2024-005',
    patientId: 'pat-004',
    patientName: 'Emily Davis',
    patientMRN: 'MRN-10004',
    patientDOB: '1995-01-30',
    orderType: 'lab',
    status: 'ordered',
    priority: 'routine',
    tests: [MOCK_LAB_TESTS.find(t => t.code === 'HBA1C')!],
    orderingProviderId: 'provider-1',
    orderingProviderName: 'Dr. Sarah Chen',
    performingLabId: 'lab-001',
    performingLabName: 'Quest Diagnostics - Main',
    diagnosisCodes: ['R73.09'],
    clinicalNotes: 'Pre-diabetes screening',
    fastingRequired: false,
    specimenType: 'blood',
    orderedDate: daysAgo(0),
    patientInstructions: 'No fasting required. Please go to Quest Diagnostics within 7 days.',
    results: [],
    resultsSummary: 'pending',
    createdAt: daysAgo(0),
    createdBy: 'provider-1',
    updatedAt: daysAgo(0),
    updatedBy: 'provider-1',
  },
  {
    id: 'order-006',
    orderId: 'ORD-2024-006',
    patientId: 'pat-005',
    patientName: 'Robert Wilson',
    patientMRN: 'MRN-10005',
    patientDOB: '1962-09-12',
    orderType: 'lab',
    status: 'final',
    priority: 'stat',
    tests: [MOCK_LAB_TESTS.find(t => t.code === 'TROP')!],
    orderingProviderId: 'provider-2',
    orderingProviderName: 'Dr. Michael Rodriguez',
    performingLabId: 'lab-003',
    performingLabName: 'Springfield General Hospital Lab',
    diagnosisCodes: ['R07.9'],
    clinicalNotes: 'Chest pain evaluation, rule out ACS',
    fastingRequired: false,
    specimenType: 'blood',
    orderedDate: daysAgo(3),
    collectionDate: daysAgo(3),
    reportedDate: daysAgo(3),
    results: [
      { id: 'res-060', orderId: 'order-006', testId: 'test-060', testCode: 'TROP', testName: 'Troponin I', value: '0.02', valueType: 'numeric', unit: 'ng/mL', referenceRange: '<0.04', referenceHigh: 0.04, interpretation: 'normal', interpretationText: 'Within normal limits, low probability of acute MI', isAbnormal: false, isCritical: false, status: 'final', reportedAt: daysAgo(3) },
    ],
    resultsSummary: 'normal',
    createdAt: daysAgo(3),
    createdBy: 'provider-2',
    updatedAt: daysAgo(3),
    updatedBy: 'system',
  },
  {
    id: 'order-007',
    orderId: 'ORD-2024-007',
    patientId: 'pat-001',
    patientName: 'John Smith',
    patientMRN: 'MRN-10001',
    patientDOB: '1985-03-15',
    orderType: 'lab',
    status: 'final',
    priority: 'routine',
    tests: [MOCK_LAB_TESTS.find(t => t.code === 'HBA1C')!],
    orderingProviderId: 'provider-1',
    orderingProviderName: 'Dr. Sarah Chen',
    performingLabId: 'lab-001',
    performingLabName: 'Quest Diagnostics - Main',
    diagnosisCodes: ['E11.9'],
    clinicalNotes: 'Quarterly diabetes monitoring',
    fastingRequired: false,
    specimenType: 'blood',
    orderedDate: daysAgo(7),
    collectionDate: daysAgo(5),
    reportedDate: daysAgo(4),
    results: [
      { 
        id: 'res-050', 
        orderId: 'order-007', 
        testId: 'test-050', 
        testCode: 'HBA1C', 
        testName: 'Hemoglobin A1c', 
        value: '7.2', 
        valueType: 'numeric', 
        unit: '%', 
        referenceRange: '<5.7 (normal), 5.7-6.4 (prediabetes), ≥6.5 (diabetes)', 
        interpretation: 'abnormal', 
        interpretationText: 'Diabetic range - above target of <7% for most adults with diabetes',
        isAbnormal: true, 
        isCritical: false, 
        status: 'final', 
        reportedAt: daysAgo(4),
        delta: {
          previousValue: '7.8',
          previousDate: daysAgo(90),
          changePercent: -7.7,
          trend: 'decreasing'
        },
        providerComments: 'Improved from last quarter. Continue current regimen.'
      },
    ],
    resultsSummary: 'abnormal',
    createdAt: daysAgo(7),
    createdBy: 'provider-1',
    updatedAt: daysAgo(4),
    updatedBy: 'system',
  },
];
