import { Encounter, EncounterTemplate } from '../../models/encounter.model';

const today = new Date();
today.setHours(0, 0, 0, 0);

function getDateWithTime(daysOffset: number, hours: number, minutes: number = 0): Date {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  date.setHours(hours, minutes, 0, 0);
  return date;
}

export const MOCK_ENCOUNTERS: Encounter[] = [
  // Today's encounters
  {
    id: 'enc-001',
    status: 'finished',
    class: 'ambulatory',
    patient: {
      id: 'pat-001',
      name: 'Sarah Johnson',
      dob: '1985-03-15',
      mrn: 'MRN-001',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    },
    provider: {
      id: 'prov-001',
      name: 'Dr. Emily Chen',
      specialty: 'Family Medicine',
    },
    startTime: getDateWithTime(0, 8, 0),
    endTime: getDateWithTime(0, 8, 40),
    duration: 40,
    facilityId: 'fac-001',
    facilityName: 'Main Street Clinic',
    roomId: 'room-101',
    roomName: 'Exam Room 1',
    appointmentId: 'apt-001',
    vitalSigns: {
      id: 'vs-001',
      encounterId: 'enc-001',
      recordedAt: getDateWithTime(0, 8, 5),
      recordedBy: 'nurse-001',
      heightCm: 165,
      weightKg: 68,
      bmi: 25.0,
      temperatureCelsius: 36.8,
      temperatureLocation: 'oral',
      pulseRate: 72,
      pulseRhythm: 'regular',
      respiratoryRate: 16,
      bloodPressureSystolic: 118,
      bloodPressureDiastolic: 76,
      bloodPressurePosition: 'sitting',
      oxygenSaturation: 98,
      painLevel: 0,
    },
    subjective: {
      chiefComplaint: 'Annual physical examination',
      historyOfPresentIllness: 'Patient presents for routine annual physical. No new complaints. Generally feeling well.',
      reviewOfSystems: {
        constitutional: 'No fever, chills, or weight changes',
        cardiovascular: 'No chest pain, palpitations, or edema',
        respiratory: 'No cough, shortness of breath, or wheezing',
        gastrointestinal: 'No nausea, vomiting, or abdominal pain',
        neurological: 'No headaches, dizziness, or numbness',
      },
      medications: 'None currently',
      allergies: 'NKDA',
    },
    objective: {
      physicalExam: {
        general: 'Well-appearing female in no acute distress',
        head: 'Normocephalic, atraumatic',
        eyes: 'PERRLA, EOM intact',
        ears: 'TMs clear bilaterally',
        throat: 'Oropharynx clear, no erythema',
        neck: 'Supple, no lymphadenopathy',
        heart: 'RRR, no murmurs',
        lungs: 'CTA bilaterally',
        abdomen: 'Soft, non-tender, no organomegaly',
        extremities: 'No edema, pulses 2+ throughout',
        skin: 'No rashes or lesions',
        neurological: 'Alert and oriented x3, CN II-XII intact',
      },
    },
    assessment: {
      clinicalImpression: 'Healthy adult female presenting for routine examination. All findings within normal limits.',
      diagnoses: [
        {
          id: 'dx-001',
          code: 'Z00.00',
          codeSystem: 'ICD-10',
          description: 'Encounter for general adult medical examination without abnormal findings',
          type: 'primary',
          status: 'active',
        },
      ],
    },
    plan: {
      treatmentPlan: 'Continue healthy lifestyle. Age-appropriate cancer screenings discussed. Immunizations up to date.',
      labOrders: [
        {
          id: 'lab-001',
          testName: 'Complete Metabolic Panel',
          loincCode: '24323-8',
          indication: 'Annual screening',
          urgency: 'routine',
          fastingRequired: true,
          status: 'ordered',
        },
        {
          id: 'lab-002',
          testName: 'Lipid Panel',
          loincCode: '24331-1',
          indication: 'Cardiovascular screening',
          urgency: 'routine',
          fastingRequired: true,
          status: 'ordered',
        },
      ],
      followUp: {
        timing: '1 year',
        reason: 'Annual physical',
      },
      patientEducation: 'Discussed importance of regular exercise, balanced diet, and routine screenings.',
    },
    billingCodes: [
      { code: '99395', codeSystem: 'CPT', description: 'Periodic preventive visit, 18-39 years' },
    ],
    createdAt: getDateWithTime(0, 8, 0),
    createdBy: 'prov-001',
    updatedAt: getDateWithTime(0, 8, 40),
    signedAt: getDateWithTime(0, 8, 45),
    signedBy: 'prov-001',
    attestation: 'I attest that this documentation is accurate and complete.',
  },
  {
    id: 'enc-002',
    status: 'finished',
    class: 'ambulatory',
    patient: {
      id: 'pat-002',
      name: 'Michael Chen',
      dob: '1962-07-22',
      mrn: 'MRN-002',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael',
    },
    provider: {
      id: 'prov-001',
      name: 'Dr. Emily Chen',
      specialty: 'Family Medicine',
    },
    startTime: getDateWithTime(0, 9, 0),
    endTime: getDateWithTime(0, 9, 18),
    duration: 18,
    facilityId: 'fac-001',
    facilityName: 'Main Street Clinic',
    appointmentId: 'apt-002',
    vitalSigns: {
      id: 'vs-002',
      encounterId: 'enc-002',
      recordedAt: getDateWithTime(0, 9, 3),
      recordedBy: 'nurse-001',
      heightCm: 175,
      weightKg: 82,
      bmi: 26.8,
      temperatureCelsius: 36.7,
      pulseRate: 78,
      bloodPressureSystolic: 138,
      bloodPressureDiastolic: 86,
      bloodPressurePosition: 'sitting',
      oxygenSaturation: 97,
    },
    subjective: {
      chiefComplaint: 'Diabetes follow-up',
      historyOfPresentIllness: 'Patient with Type 2 DM for 5 years, on Metformin. Reports good compliance with medications. Checking blood sugars at home, averaging 130-150 fasting.',
      medications: 'Metformin 1000mg BID, Lisinopril 10mg daily',
      allergies: 'Penicillin (rash)',
    },
    objective: {
      physicalExam: {
        general: 'Well-appearing male in no distress',
        heart: 'RRR, no murmurs',
        lungs: 'CTA bilaterally',
        extremities: 'No edema, sensation intact to monofilament',
      },
      labResults: 'Recent HbA1c: 7.2% (improved from 7.8%)',
    },
    assessment: {
      clinicalImpression: 'Type 2 DM with improved glycemic control. Continue current regimen.',
      diagnoses: [
        {
          id: 'dx-002',
          code: 'E11.9',
          codeSystem: 'ICD-10',
          description: 'Type 2 diabetes mellitus without complications',
          type: 'primary',
          status: 'active',
          onsetDate: new Date(today.getTime() - 5 * 365 * 24 * 60 * 60 * 1000),
        },
        {
          id: 'dx-003',
          code: 'I10',
          codeSystem: 'ICD-10',
          description: 'Essential (primary) hypertension',
          type: 'secondary',
          status: 'active',
        },
      ],
    },
    plan: {
      treatmentPlan: 'Continue Metformin and Lisinopril. Reinforce diet and exercise.',
      medications: [
        {
          id: 'med-001',
          medicationName: 'Metformin',
          dosage: '1000mg',
          frequency: 'twice daily',
          route: 'oral',
          refills: 3,
          status: 'active',
        },
      ],
      labOrders: [
        {
          id: 'lab-003',
          testName: 'HbA1c',
          indication: 'Diabetes monitoring',
          urgency: 'routine',
          status: 'ordered',
        },
      ],
      followUp: {
        timing: '3 months',
        reason: 'Diabetes follow-up',
      },
    },
    billingCodes: [
      { code: '99214', codeSystem: 'CPT', description: 'Office visit, established patient, moderate complexity' },
    ],
    createdAt: getDateWithTime(0, 9, 0),
    createdBy: 'prov-001',
    signedAt: getDateWithTime(0, 9, 20),
    signedBy: 'prov-001',
  },
  {
    id: 'enc-003',
    status: 'in-progress',
    class: 'ambulatory',
    patient: {
      id: 'pat-003',
      name: 'Emily Rodriguez',
      dob: '1995-11-08',
      mrn: 'MRN-003',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    },
    provider: {
      id: 'prov-001',
      name: 'Dr. Emily Chen',
      specialty: 'Family Medicine',
    },
    startTime: getDateWithTime(0, 10, 0),
    facilityId: 'fac-001',
    facilityName: 'Main Street Clinic',
    roomId: 'room-101',
    roomName: 'Exam Room 1',
    appointmentId: 'apt-003',
    vitalSigns: {
      id: 'vs-003',
      encounterId: 'enc-003',
      recordedAt: getDateWithTime(0, 10, 5),
      recordedBy: 'nurse-001',
      heightCm: 160,
      weightKg: 58,
      bmi: 22.7,
      temperatureCelsius: 36.9,
      pulseRate: 80,
      bloodPressureSystolic: 110,
      bloodPressureDiastolic: 70,
      oxygenSaturation: 99,
    },
    subjective: {
      chiefComplaint: 'New patient visit',
      historyOfPresentIllness: 'New patient establishing care. Recently moved to area. Generally healthy, no chronic conditions.',
    },
    createdAt: getDateWithTime(0, 10, 0),
    createdBy: 'prov-001',
  },
  // Yesterday's encounters
  {
    id: 'enc-004',
    status: 'finished',
    class: 'ambulatory',
    patient: {
      id: 'pat-004',
      name: 'Robert Williams',
      dob: '1978-02-14',
      mrn: 'MRN-004',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=robert',
    },
    provider: {
      id: 'prov-001',
      name: 'Dr. Emily Chen',
      specialty: 'Family Medicine',
    },
    startTime: getDateWithTime(-1, 11, 0),
    endTime: getDateWithTime(-1, 11, 25),
    duration: 25,
    facilityId: 'fac-001',
    facilityName: 'Main Street Clinic',
    vitalSigns: {
      id: 'vs-004',
      encounterId: 'enc-004',
      recordedAt: getDateWithTime(-1, 11, 5),
      recordedBy: 'nurse-001',
      heightCm: 180,
      weightKg: 88,
      temperatureCelsius: 38.2,
      pulseRate: 92,
      bloodPressureSystolic: 125,
      bloodPressureDiastolic: 82,
      oxygenSaturation: 97,
    },
    subjective: {
      chiefComplaint: 'Fever and cough',
      historyOfPresentIllness: 'Patient presents with 3-day history of fever (up to 101F), productive cough with yellow sputum, and fatigue. No shortness of breath.',
      reviewOfSystems: {
        constitutional: 'Fever, chills, fatigue',
        respiratory: 'Productive cough, no SOB',
        gastrointestinal: 'Mild nausea, decreased appetite',
      },
    },
    objective: {
      physicalExam: {
        general: 'Ill-appearing male, alert',
        throat: 'Mild pharyngeal erythema',
        neck: 'Anterior cervical lymphadenopathy',
        lungs: 'Scattered rhonchi, no wheezes',
      },
    },
    assessment: {
      clinicalImpression: 'Acute bronchitis, likely viral etiology',
      diagnoses: [
        {
          id: 'dx-004',
          code: 'J20.9',
          codeSystem: 'ICD-10',
          description: 'Acute bronchitis, unspecified',
          type: 'primary',
          status: 'active',
          onsetDate: getDateWithTime(-4, 0, 0),
        },
      ],
    },
    plan: {
      treatmentPlan: 'Supportive care. Push fluids, rest. Return if symptoms worsen or persist >10 days.',
      medications: [
        {
          id: 'med-002',
          medicationName: 'Benzonatate',
          dosage: '100mg',
          frequency: 'three times daily',
          route: 'oral',
          duration: '7 days',
          quantity: 21,
          instructions: 'Take with water, do not chew',
          status: 'active',
        },
      ],
      followUp: {
        timing: 'PRN',
        reason: 'If symptoms worsen or no improvement in 10 days',
      },
    },
    billingCodes: [
      { code: '99213', codeSystem: 'CPT', description: 'Office visit, established patient, low complexity' },
    ],
    createdAt: getDateWithTime(-1, 11, 0),
    createdBy: 'prov-001',
    signedAt: getDateWithTime(-1, 11, 30),
    signedBy: 'prov-001',
  },
  {
    id: 'enc-005',
    status: 'finished',
    class: 'virtual',
    patient: {
      id: 'pat-006',
      name: 'David Martinez',
      dob: '1988-09-30',
      mrn: 'MRN-006',
    },
    provider: {
      id: 'prov-001',
      name: 'Dr. Emily Chen',
      specialty: 'Family Medicine',
    },
    startTime: getDateWithTime(-1, 14, 0),
    endTime: getDateWithTime(-1, 14, 15),
    duration: 15,
    subjective: {
      chiefComplaint: 'Medication refill',
      historyOfPresentIllness: 'Patient requests refill of Atorvastatin. No new symptoms. Taking medication as prescribed.',
      medications: 'Atorvastatin 20mg daily',
    },
    assessment: {
      clinicalImpression: 'Hyperlipidemia, stable on current therapy',
      diagnoses: [
        {
          id: 'dx-005',
          code: 'E78.5',
          codeSystem: 'ICD-10',
          description: 'Hyperlipidemia, unspecified',
          type: 'primary',
          status: 'active',
        },
      ],
    },
    plan: {
      treatmentPlan: 'Continue Atorvastatin. Lipid panel due before next visit.',
      medications: [
        {
          id: 'med-003',
          medicationName: 'Atorvastatin',
          dosage: '20mg',
          frequency: 'once daily',
          route: 'oral',
          refills: 3,
          status: 'active',
        },
      ],
      labOrders: [
        {
          id: 'lab-004',
          testName: 'Lipid Panel',
          urgency: 'routine',
          fastingRequired: true,
          status: 'ordered',
        },
      ],
      followUp: {
        timing: '6 months',
        reason: 'Lipid management',
      },
    },
    billingCodes: [
      { code: '99213', codeSystem: 'CPT', description: 'Office visit, established patient, low complexity' },
      { code: '99421', codeSystem: 'CPT', description: 'Online digital E/M service' },
    ],
    createdAt: getDateWithTime(-1, 14, 0),
    createdBy: 'prov-001',
    signedAt: getDateWithTime(-1, 14, 20),
    signedBy: 'prov-001',
  },
  // Last week
  {
    id: 'enc-006',
    status: 'finished',
    class: 'ambulatory',
    patient: {
      id: 'pat-005',
      name: 'Jennifer Davis',
      dob: '1972-05-18',
      mrn: 'MRN-005',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jennifer',
    },
    provider: {
      id: 'prov-001',
      name: 'Dr. Emily Chen',
      specialty: 'Family Medicine',
    },
    startTime: getDateWithTime(-5, 10, 30),
    endTime: getDateWithTime(-5, 11, 0),
    duration: 30,
    facilityId: 'fac-001',
    facilityName: 'Main Street Clinic',
    subjective: {
      chiefComplaint: 'Anxiety and sleep problems',
      historyOfPresentIllness: 'Patient reports increasing anxiety over past 2 months with difficulty falling asleep. Work stress contributing. No suicidal ideation.',
      socialHistory: 'Recently promoted, increased work responsibilities. Drinks 2-3 cups coffee daily. No alcohol or drugs.',
    },
    assessment: {
      clinicalImpression: 'Generalized anxiety disorder with insomnia',
      diagnoses: [
        {
          id: 'dx-006',
          code: 'F41.1',
          codeSystem: 'ICD-10',
          description: 'Generalized anxiety disorder',
          type: 'primary',
          status: 'active',
        },
        {
          id: 'dx-007',
          code: 'G47.00',
          codeSystem: 'ICD-10',
          description: 'Insomnia, unspecified',
          type: 'secondary',
          status: 'active',
        },
      ],
    },
    plan: {
      treatmentPlan: 'Start low-dose SSRI. Sleep hygiene education. Consider therapy referral.',
      medications: [
        {
          id: 'med-004',
          medicationName: 'Sertraline',
          dosage: '25mg',
          frequency: 'once daily in the morning',
          route: 'oral',
          duration: '1 month trial',
          quantity: 30,
          instructions: 'Take with food. May cause initial side effects that typically improve.',
          status: 'active',
        },
      ],
      referrals: [
        {
          id: 'ref-001',
          specialty: 'Psychiatry/Counseling',
          reason: 'Cognitive behavioral therapy for anxiety and insomnia',
          urgency: 'routine',
          status: 'pending',
        },
      ],
      patientEducation: 'Discussed sleep hygiene: consistent sleep schedule, limit screen time before bed, avoid caffeine after noon.',
      followUp: {
        timing: '4 weeks',
        reason: 'SSRI follow-up',
      },
    },
    billingCodes: [
      { code: '99214', codeSystem: 'CPT', description: 'Office visit, established patient, moderate complexity' },
    ],
    createdAt: getDateWithTime(-5, 10, 30),
    createdBy: 'prov-001',
    signedAt: getDateWithTime(-5, 11, 5),
    signedBy: 'prov-001',
  },
];

export const MOCK_ENCOUNTER_TEMPLATES: EncounterTemplate[] = [
  {
    id: 'tmpl-001',
    name: 'Annual Physical - Adult',
    description: 'Standard template for adult wellness examination',
    category: 'Preventive',
    encounterClass: 'ambulatory',
    subjective: {
      chiefComplaint: 'Annual physical examination',
      historyOfPresentIllness: 'Patient presents for routine annual physical examination.',
      reviewOfSystems: {
        constitutional: '',
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
      },
    },
    objective: {
      physicalExam: {
        general: 'Well-appearing in no acute distress',
        head: 'Normocephalic, atraumatic',
        eyes: 'PERRLA, EOM intact',
        ears: 'TMs clear bilaterally',
        throat: 'Oropharynx clear',
        neck: 'Supple, no lymphadenopathy',
        heart: 'RRR, no murmurs',
        lungs: 'CTA bilaterally',
        abdomen: 'Soft, non-tender, no organomegaly',
        extremities: 'No edema',
        neurological: 'Alert and oriented x3',
      },
    },
    plan: {
      treatmentPlan: 'Continue healthy lifestyle. Age-appropriate screenings reviewed.',
      followUp: {
        timing: '1 year',
        reason: 'Annual physical',
      },
    },
    createdBy: 'system',
    isShared: true,
    usageCount: 156,
  },
  {
    id: 'tmpl-002',
    name: 'URI - Acute Visit',
    description: 'Template for upper respiratory infection visit',
    category: 'Acute',
    encounterClass: 'ambulatory',
    subjective: {
      chiefComplaint: 'Cold symptoms',
      historyOfPresentIllness: 'Patient presents with ___ day history of nasal congestion, sore throat, and cough.',
      reviewOfSystems: {
        constitutional: '',
        respiratory: '',
      },
    },
    objective: {
      physicalExam: {
        general: '',
        throat: '',
        ears: '',
        lungs: '',
        neck: '',
      },
    },
    assessment: {
      clinicalImpression: 'Acute upper respiratory infection, likely viral',
      diagnoses: [
        {
          id: 'tmpl-dx-001',
          code: 'J06.9',
          codeSystem: 'ICD-10',
          description: 'Acute upper respiratory infection, unspecified',
          type: 'primary',
          status: 'active',
        },
      ],
    },
    plan: {
      treatmentPlan: 'Supportive care. Push fluids, rest.',
      followUp: {
        timing: 'PRN',
        reason: 'If symptoms worsen or do not improve in 7-10 days',
      },
    },
    createdBy: 'system',
    isShared: true,
    usageCount: 89,
  },
  {
    id: 'tmpl-003',
    name: 'Diabetes Follow-up',
    description: 'Template for Type 2 DM follow-up visit',
    category: 'Chronic Disease',
    encounterClass: 'ambulatory',
    subjective: {
      chiefComplaint: 'Diabetes follow-up',
      historyOfPresentIllness: 'Patient with Type 2 DM presents for routine follow-up. Current medications: ___.',
    },
    objective: {
      physicalExam: {
        general: '',
        heart: '',
        extremities: 'Sensation intact to monofilament testing',
      },
      labResults: 'Recent HbA1c: ___',
    },
    plan: {
      treatmentPlan: 'Continue current diabetes management.',
      labOrders: [
        {
          id: 'tmpl-lab-001',
          testName: 'HbA1c',
          indication: 'Diabetes monitoring',
          urgency: 'routine',
          status: 'ordered',
        },
        {
          id: 'tmpl-lab-002',
          testName: 'Comprehensive Metabolic Panel',
          indication: 'Kidney function monitoring',
          urgency: 'routine',
          status: 'ordered',
        },
      ],
      followUp: {
        timing: '3 months',
        reason: 'Diabetes management',
      },
    },
    createdBy: 'system',
    isShared: true,
    usageCount: 124,
  },
  {
    id: 'tmpl-004',
    name: 'Hypertension Follow-up',
    description: 'Template for HTN management visit',
    category: 'Chronic Disease',
    encounterClass: 'ambulatory',
    subjective: {
      chiefComplaint: 'Blood pressure follow-up',
      historyOfPresentIllness: 'Patient with essential hypertension presents for follow-up. Current medications: ___. Reports compliance with medications.',
    },
    objective: {
      physicalExam: {
        general: '',
        heart: '',
        lungs: '',
      },
    },
    assessment: {
      clinicalImpression: 'Essential hypertension',
      diagnoses: [
        {
          id: 'tmpl-dx-002',
          code: 'I10',
          codeSystem: 'ICD-10',
          description: 'Essential (primary) hypertension',
          type: 'primary',
          status: 'active',
        },
      ],
    },
    plan: {
      treatmentPlan: 'Continue antihypertensive therapy. Lifestyle modifications reinforced.',
      followUp: {
        timing: '3 months',
        reason: 'Blood pressure management',
      },
    },
    createdBy: 'system',
    isShared: true,
    usageCount: 98,
  },
  {
    id: 'tmpl-005',
    name: 'Well Child - Pediatric',
    description: 'Template for pediatric wellness visit',
    category: 'Preventive',
    encounterClass: 'ambulatory',
    subjective: {
      chiefComplaint: 'Well child visit',
      historyOfPresentIllness: 'Child presents for routine well child examination.',
      socialHistory: 'Development: ___. School performance: ___.',
    },
    objective: {
      physicalExam: {
        general: 'Well-appearing child, active and alert',
        head: 'Normocephalic',
        eyes: 'Red reflex present bilaterally',
        ears: 'TMs clear',
        heart: 'RRR, no murmurs',
        lungs: 'CTA',
        abdomen: 'Soft, non-tender',
        extremities: 'Full ROM, normal gait',
        neurological: 'Age-appropriate development',
      },
    },
    plan: {
      treatmentPlan: 'Age-appropriate immunizations administered. Anticipatory guidance provided.',
      followUp: {
        timing: 'Per schedule',
        reason: 'Well child visit',
      },
    },
    createdBy: 'system',
    isShared: true,
    usageCount: 67,
  },
];
