name: Auto merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
    auto_merge:
        runs-on: ubuntu-latest

        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            ## Auto approve the PR
            - name: Approve the PR
              uses: juliangruber/approve-pull-request-action@v2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                number: ${{ github.event.pull_request.number }}

            ## Merge the PR
            - name: Merge the PR
              uses: pascalgn/automerge-action@v0.16.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  delete-branch: true
                  merge-method: squash
                  commit-message: 'Auto-merged by Dependabot'
